import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const numberLike = v.union(v.number(), v.int64());
const optionalNumberLike = v.optional(numberLike);

export default defineSchema({
  users: defineTable({
    clerkId: v.optional(v.string()),
    anonymousId: v.optional(v.string()),
    mergedIntoClerkId: v.optional(v.string()),
    credits: numberLike,
    diamondBalance: optionalNumberLike,
    premiumCredits: optionalNumberLike,
    diamondSources: v.optional(v.array(v.union(v.literal("daily_free"), v.literal("purchased_pack"), v.literal("referral")))),
    plan: v.string(),
    generationCount: numberLike,
    reviewPrompted: v.boolean(),
    lastReviewPromptAt: optionalNumberLike,
    firstDiamondRatingPromptedAt: optionalNumberLike,
    lastRewardDate: optionalNumberLike,
    streakCount: optionalNumberLike,
    lastLoginDate: optionalNumberLike,
    lastClaimDate: optionalNumberLike,
    lastClaimAt: v.optional(v.union(numberLike, v.null())),
    nextDiamondClaimAt: optionalNumberLike,
    canClaimDiamond: v.optional(v.boolean()),
    eliteProUntil: optionalNumberLike,
    proTrialExpiresAt: v.optional(v.union(numberLike, v.null())),
    welcomeDiamondGiven: v.optional(v.boolean()),
    proTrialEndedPaywallPending: v.optional(v.boolean()),
    proTrialEndedPaywallShownAt: optionalNumberLike,
    onboardingDiamondClaimedAt: optionalNumberLike,
    firstEntryRewardDismissedAt: optionalNumberLike,
    referralCode: v.optional(v.string()),
    referralCount: optionalNumberLike,
    referralProCount: optionalNumberLike,
    referredBy: v.optional(v.string()),
    referralInstallRewardedAt: optionalNumberLike,
    referralProRewardedAt: optionalNumberLike,
    subscriptionType: v.optional(v.union(v.literal("weekly"), v.literal("yearly"), v.literal("free"))),
    subscriptionEntitlement: v.optional(v.union(v.literal("weekly_pro"), v.literal("annual_pro"), v.literal("free"))),
    subscriptionStartedAt: optionalNumberLike,
    subscriptionEnd: optionalNumberLike,
    imageLimit: optionalNumberLike,
    imageGenerationCount: optionalNumberLike,
    lastResetDate: optionalNumberLike,
    pricingTier: v.optional(v.string()),
    pricingCountryCode: v.optional(v.string()),
    pricingCurrencyCode: v.optional(v.string()),
    expoPushToken: v.optional(v.string()),
    devicePushToken: v.optional(v.string()),
    notificationPlatform: v.optional(v.string()),
    notificationsDeclined: v.optional(v.boolean()),
    notificationsPermissionRequestedAt: optionalNumberLike,
    notificationsPermissionGrantedAt: optionalNumberLike,
    proTipNotificationIndex: optionalNumberLike,
  })
    .index("by_clerkId", ["clerkId"])
    .index("by_anonymousId", ["anonymousId"])
    .index("by_referralCode", ["referralCode"])
    .index("by_proTrialExpiresAt", ["proTrialExpiresAt"]),

  generations: defineTable({
    userId: v.string(),
    sourceImageStorageId: v.optional(v.id("_storage")),
    referenceImageStorageIds: v.optional(v.array(v.id("_storage"))),
    maskImageStorageId: v.optional(v.id("_storage")),
    storageId: v.optional(v.id("_storage")),
    imageUrl: v.optional(v.string()),
    watermarkRequired: v.optional(v.boolean()),
    prompt: v.optional(v.string()),
    style: v.optional(v.string()),
    styleSelections: v.optional(v.array(v.string())),
    roomType: v.optional(v.string()),
    customPrompt: v.optional(v.string()),
    colorPalette: v.optional(v.string()),
    aspectRatio: v.optional(v.string()),
    serviceType: v.optional(v.union(v.literal("paint"), v.literal("floor"), v.literal("redesign"), v.literal("layout"), v.literal("reference"), v.literal("replace"), v.literal("interior"), v.literal("exterior"), v.literal("garden"), v.literal("wall"), v.literal("transfer"))),
    modeId: v.optional(v.string()),
    paletteId: v.optional(v.string()),
    finishId: v.optional(v.string()),
    aiSuggestedStyle: v.optional(v.string()),
    aiSuggestedPaletteId: v.optional(v.string()),
    smartSuggest: v.optional(v.boolean()),
    mode: v.optional(v.string()),
    qualityTier: v.optional(v.union(v.literal("free"), v.literal("standard_hd"), v.literal("premium"))),
    renderQuality: v.optional(v.union(v.literal("medium"), v.literal("high"))),
    renderCostUsd: optionalNumberLike,
    estimatedCostUsd: optionalNumberLike,
    applyWatermark: v.optional(v.boolean()),
    renderUserTier: v.optional(v.union(v.literal("free"), v.literal("paid"))),
    diamondSource: v.optional(v.union(v.literal("daily_free"), v.literal("purchased_pack"), v.literal("referral"))),
    outputResolution: v.optional(v.string()),
    speedTier: v.optional(v.union(v.literal("standard"), v.literal("pro"), v.literal("ultra"))),
    status: v.optional(v.union(v.literal("processing"), v.literal("ready"), v.literal("failed"))),
    errorMessage: v.optional(v.string()),
    planUsed: v.string(),
    createdAt: optionalNumberLike,
    completedAt: optionalNumberLike,
    isFavorite: v.optional(v.boolean()),
    feedback: v.optional(v.string()),
    feedbackReason: v.optional(v.string()),
    retryGranted: v.optional(v.boolean()),
    projectId: v.optional(v.id("projects")),
  }).index("by_userId", ["userId"]),

  projects: defineTable({
    userId: v.string(),
    name: v.string(),
    createdAt: numberLike,
  }).index("by_userId", ["userId"]),

  feedback: defineTable({
    userId: v.string(),
    kind: v.optional(v.union(v.literal("message"), v.literal("generation_review"))),
    message: v.optional(v.string()),
    generationId: v.optional(v.id("generations")),
    imageId: v.optional(v.id("generations")),
    sentiment: v.optional(v.union(v.literal("liked"), v.literal("disliked"))),
    isLike: v.optional(v.boolean()),
    styleSelected: v.optional(v.string()),
    serviceType: v.optional(v.string()),
    roomLabel: v.optional(v.string()),
    source: v.optional(v.string()),
    createdAt: numberLike,
    generationCount: optionalNumberLike,
  })
    .index("by_userId", ["userId"])
    .index("by_generationId", ["generationId"]),

  diamondPurchases: defineTable({
    transactionId: v.string(),
    userId: v.string(),
    productIdentifier: v.string(),
    packageIdentifier: v.optional(v.string()),
    packId: v.string(),
    diamonds: numberLike,
    amount: numberLike,
    currencyCode: v.string(),
    countryCode: v.optional(v.string()),
    pricingTier: v.optional(v.string()),
    purchasedAt: numberLike,
    createdAt: numberLike,
  })
    .index("by_transactionId", ["transactionId"])
    .index("by_userId", ["userId"]),

  renders: defineTable({
    userId: v.string(),
    quality: v.union(v.literal("medium"), v.literal("high")),
    costUsd: numberLike,
    timestamp: numberLike,
    userTier: v.union(v.literal("free"), v.literal("paid")),
  })
    .index("by_userId", ["userId"])
    .index("by_timestamp", ["timestamp"]),
});
