#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os

path = r'C:\Users\LENOVO\Desktop\HomeDecor AI (App)\app\src\main\res\values-ar\strings.xml'

lines = []
lines.append('<?xml version="1.0" encoding="utf-8"?>')
lines.append('<resources>')

strings = {
    "app_name": "HomeDecor AI",
    "nav_tools": "الأدوات",
    "nav_discover": "اكتشف",
    "discover_styles_title": "اكتشف الأنماط",
    "photos": "الصور",
    "nav_my_board": "الملف الشخصي",
    "nav_upgrade_pro": "الترقية إلى PRO",
    "nav_profile": "الإعدادات",
    "paywall_cmp_energy": "الطاقة",
    "paywall_cmp_energy_free": "3",
    "paywall_cmp_energy_pro": "\\u221E غير محدود",
    "paywall_cmp_4k_export": "تصدير 4K",
    "paywall_cmp_4k_export_free": "HD",
    "paywall_cmp_4k_export_pro": "مشمول",
    "paywall_cmp_no_watermark": "بدون علامة مائية",
    "paywall_cmp_no_watermark_free": "نعم",
    "paywall_cmp_no_watermark_pro": "بدون علامة مائية \\u2713",
    "paywall_cmp_ai_speed": "سرعة الذكاء الاصطناعي",
    "paywall_cmp_ai_speed_free": "قياسي",
    "paywall_cmp_ai_speed_pro": "أولوية",
    "pro": "Pro",
    "pro_upper": "PRO",
    "upgrade_to_pro": "الترقية إلى Pro",
    "try_this": "جرّب هذا",
    "continue_action": "متابعة",
    "generate": "إنشاء",
    "generate_my_design": "أنشئ تصميمي",
    "try_with_example": "جرّب مع مثال",
    "back": "رجوع",
    "close": "إغلاق",
    "return_back": "رجوع",
    "gallery": "المعرض",
    "camera": "الكاميرا",
    "example": "مثال",
    "use_example": "استخدم مثالاً",
    "example_photos": "صور نموذجية",
    "import_action": "استيراد",
    "import_photo": "استيراد صورة",
    "import_plus": "استيراد +",
    "photo_added": "تمت إضافة الصورة",
    "photo_number": "الصورة %1$d",
    "remove_photo": "إزالة الصورة",
    "add_photo": "إضافة صورة",
    "step_count_format": "الخطوة %1$d/%2$d",
    "result": "النتيجة",
    "unavailable": "غير متاح",
    "ellipsis": "...",
    "loading_ellipsis": "جارٍ التحميل...",
    "processing_ellipsis": "جارٍ المعالجة...",
    "progress_preparing_studio": "جارٍ تحضير الاستوديو...",
    "progress_analyzing_image": "جارٍ تحليل الصورة...",
    "progress_applying_color": "جارٍ تطبيق خيارات التصميم...",
    "progress_finalizing_render": "جارٍ إتمام التصيير...",
    "tool_interior_title": "التصميم الداخلي",
    "tool_interior_description": "أعد تصميم مساحتك بالذكاء الاصطناعي.",
    "tool_facade_title": "التصميم الخارجي",
    "tool_facade_description": "أعد تصميم واجهة منزلك بنمط معماري عالمي.",
    "tool_garden_title": "تصميم الحديقة",
    "tool_garden_description": "صمّم حدائق ومساحات خارجية مذهلة بسهولة.",
    "tool_paint_title": "الطلاء الذكي",
    "tool_paint_description": "حسّن جدرانك بألوان مخصصة وملامس تصميمية.",
    "tool_floor_title": "تجديد الأرضية",
    "tool_floor_description": "ارتقِ بأساس غرفتك بمواد وتشطيبات فاخرة.",
    "tool_layout_title": "تخطيط ذكي",
    "tool_layout_description": "حسّن التخطيط لتحقيق أقصى راحة.",
    "tool_replace_title": "استبدال العناصر",
    "tool_replace_description": "حدد عنصراً في صورتك واستبدله بتعديلات دقيقة بالذكاء الاصطناعي.",
    "tool_reference_title": "نقل النمط من مرجع",
    "tool_reference_description": "استورد مرجعاً بصرياً وطبّق أسلوبه على غرفتك.",
    "workflow_interior": "التصميم الداخلي",
    "workflow_exterior": "التصميم الخارجي",
    "workflow_garden": "الحديقة",
    "workflow_paint": "الطلاء",
    "workflow_floor": "تجديد الأرضية",
    "workflow_layout": "التخطيط",
    "workflow_replace": "العناصر",
    "workflow_reference": "مرجع",
    "step_photo_facade_title": "الواجهات الخارجية",
    "step_photo_facade_body": "أعد تصميم وتحسين منزلك.",
    "step_photo_garden_title": "الحديقة",
    "step_photo_garden_body": "حوّل مساحتك الخارجية إلى مكان جاهز للعيش.",
    "step_photo_floor_title": "تغيير الأرضية",
    "step_photo_floor_body": "استورد صورة لغرفتك.",
    "step_photo_paint_title": "طلاء الجدران",
    "step_photo_paint_body": "استورد صورة لغرفتك.",
    "step_photo_layout_title": "صورة الغرفة",
    "step_photo_layout_body": "استورد صورة واسعة وواضحة لتخطيط المكان.",
    "step_photo_replace_title": "استبدال عنصر",
    "step_photo_replace_body": "استورد صورة تحتوي على العنصر المراد تعديله.",
    "step_photo_reference_title": "نمط مرجعي",
    "step_photo_reference_body": "استورد الغرفة المراد تحويلها.",
    "step_photo_interior_title": "التصميم الداخلي",
    "step_photo_interior_body": "استخدم صورة واضحة ومضاءة جيداً بزاوية واسعة.",
    "step_building_type_title": "اختر نوع المبنى",
    "step_building_type_body": "حدد الشكل المعماري الذي تريد إعادة التفكير فيه.",
    "step_choose_style_title": "اختر أسلوبك",
    "step_choose_style_body": "اختر أسلوباً مميزاً لتشكيل رؤية تصميمك.",
    "step_choose_garden_style_title": "اختر نمط الحديقة",
    "step_choose_garden_style_body": "حدد نمط المناظر الطبيعية لتوجيه إعادة تصميم مساحتك الخارجية.",
    "step_paint_surfaces_title": "حدد الأسطح المراد تحويلها",
    "step_paint_surfaces_body": "ارسم قناعاً على الجدران أو الأسطح المراد تحويلها.",
    "step_mark_floor_title": "حدد الأرضية",
    "step_mark_floor_body": "ارسم قناعاً على الأرضية المراد استبدالها.",
    "step_layout_goal_title": "ما هو هدفك؟",
    "step_layout_goal_body": "حسّن التخطيط دون فقدان هيكل الغرفة.",
    "step_mark_object_title": "حدد العنصر",
    "step_mark_object_body": "ضع قناعاً على العنصر المراد استبداله واحتفظ بباقي الصورة سليمة.",
    "step_add_reference_title": "أضف مرجعاً",
    "step_add_reference_body": "استورد صورة بالنمط المراد تطبيقه.",
    "step_choose_space_title": "اختر مساحتك",
    "step_choose_space_body": "حدد نوع الغرفة لتكيف التصيير مع المساحة.",
    "step_choose_color_title": "اختر لون الجدار",
    "step_choose_color_body": "اختر عينة للجدار المحدد فقط، ثم أضف ملاحظات تشطيب اختيارية.",
    "step_choose_material_title": "اختر المادة",
    "step_choose_material_body": "اختر عينة للأرضية المحددة فقط. سيحترم الذكاء الاصطناعي المنظور والإضاءة وظلال الأثاث.",
    "step_describe_replacement_title": "صف الاستبدال",
    "step_describe_replacement_body": "اختر اقتراحاً أو صِف بدقة العنصر الجديد المراد إدراجه.",
    "step_transfer_strength_title": "شدة النقل",
    "step_transfer_strength_body": "اختر مدى قوة توجيه النمط المرجعي للتصيير.",
    "step_style_body": "اختر الأجواء التي تريد تطبيقها على الغرفة.",
    "step_color_harmony_title": "تناغم الألوان",
    "step_color_harmony_body": "اختر لوحة ألوان قبل الإنشاء.",
    "step_describe_vision_title": "صف رؤيتك",
    "step_describe_floor_body": "صف الأرضية التي تريدها: المادة والظل والتشطيب والأجواء.",
    "step_review_edit_title": "مراجعة التعديل",
    "step_review_edit_body": "أكد الاستبدال قبل الإنشاء.",
    "step_review_transfer_title": "مراجعة النقل",
    "step_review_transfer_body": "أكد المرجع والنمط قبل الإنشاء.",
    "step_design_mode_title": "وضع التصميم",
    "step_design_mode_body": "اختر مستوى التحول.",
    "step_design_mode_color_body": "اختر الوضع وتناغم الألوان.",
    "advanced_controls": "تحكم متقدم",
    "advanced_controls_subtitle": "اختر ما الذي تريد الحفاظ عليه أو تغييره أو تجنبه.",
    "keep_controls_title": "الحفاظ",
    "change_controls_title": "التغيير",
    "preserve_rest_of_image": "الحفاظ على بقية الصورة",
    "budget_mode": "وضع الميزانية",
    "avoid_these": "تجنب هذه",
    "recent_styles": "الأنماط الأخيرة",
    "option_budget_low": "ميزانية منخفضة",
    "option_budget_medium": "ميزانية متوسطة",
    "option_budget_luxury": "فاخر",
    "option_avoid_dark_colors": "بدون ألوان داكنة",
    "option_avoid_structural_changes": "بدون تغييرات هيكلية",
    "option_avoid_plants": "بدون نباتات",
    "option_avoid_keep_windows": "الحفاظ على النوافذ",
    "option_avoid_furniture_changes": "بدون تغييرات في الأثاث",
    "option_advanced_layout": "التخطيط",
    "option_advanced_windows": "النوافذ",
    "option_advanced_floor": "الأرضية",
    "option_advanced_main_furniture": "الأثاث الرئيسي",
    "option_advanced_style": "النمط",
    "option_advanced_colors": "الألوان",
    "option_advanced_decor": "الديكور",
    "option_advanced_lighting": "الإضاءة",
    "option_advanced_structure": "الهيكل",
    "option_advanced_roof": "السطح",
    "option_advanced_entry": "المدخل",
    "option_advanced_facade": "الواجهة",
    "option_advanced_landscape": "المناظر الطبيعية",
    "option_advanced_trees": "الأشجار",
    "option_advanced_pool": "المسبح",
    "option_advanced_terrace": "الشرفة",
    "option_advanced_fence": "السياج",
    "option_advanced_plants": "النباتات",
    "option_advanced_furniture": "الأثاث",
    "option_advanced_paths": "المسارات",
    "option_advanced_walls": "الجدران",
    "option_advanced_doors": "الأبواب",
    "option_advanced_priority_furniture": "الأثاث ذو الأولوية",
    "option_advanced_organization": "التنظيم",
    "option_advanced_circulation": "الحركة",
    "option_advanced_storage": "التخزين",
    "option_advanced_zones": "المناطق",
    "option_advanced_main_colors": "الألوان الرئيسية",
    "option_advanced_mood": "الأجواء",
    "option_advanced_materials": "المواد",
    "reference_two_images_title": "اختر الصورتين",
    "reference_two_images_body": "أضف صورة في &quot;غرفتك&quot; ثم صورة في &quot;الصورة المرجعية&quot;.",
    "your_room": "غرفتك",
    "your_room_body": "صورة الغرفة المراد تحويلها.",
    "reference_image": "الصورة المرجعية",
    "reference_image_body": "النمط البصري الذي سيوجه النقل.",
    "reference_missing_both_hint": "اختر &quot;غرفتك&quot; و&quot;الصورة المرجعية&quot; لتفعيل المتابعة.",
    "reference_missing_room_hint": "اختر &quot;غرفتك&quot; للمتابعة.",
    "reference_missing_reference_hint": "اختر &quot;الصورة المرجعية&quot; للمتابعة.",
    "reference_empty_preview_title": "الصورة مطلوبة",
    "style_reference": "مرجع النمط",
    "reference_added": "تمت إضافة المرجع",
    "no_reference": "بدون مرجع",
    "reference_picker_title": "الصورة المرجعية",
    "reference_picker_body": "أضف النمط البصري لتطبيقه على غرفتك.",
    "reference_picker_selected_body": "سيستخدم النقل هذه الأجواء.",
    "reference_picker_empty_body": "استورد صورة أو استخدم المثال.",
    "editorial_reference": "مرجع تحريري",
    "mask_floor_title": "حدد الأرضية",
    "mask_floor_body": "ارسم على الأرضية المراد استبدالها فقط. مطلوب قناع حقيقي قبل الإنشاء.",
    "mask_floor_disabled": "حدد الأرضية أولاً",
    "mask_floor_description": "الأرضية المراد تغطيتها",
    "mask_floor_empty_title": "حدد الأرضية",
    "mask_floor_empty_body": "ارسم على مساحة الأرضية المراد استبدالها. غطِّ مساحة كافية لإنشاء قناع حقيقي.",
    "mask_wall_title": "حدد الجدران أو الأسطح",
    "mask_wall_body": "ارسم على الجدران أو الأسطح المراد إعادة طلائها. مطلوب قناع حقيقي قبل الإنشاء.",
    "mask_wall_disabled": "حدد الجدران أولاً",
    "mask_wall_description": "الجدران أو الأسطح المراد تغطيتها",
    "mask_wall_empty_title": "حدد الجدران أو الأسطح",
    "mask_wall_empty_body": "ارسم على كل جدار أو سطح المراد إعادة طلائه. غطِّ مساحة كافية لإنشاء قناع حقيقي.",
    "mask_object_title": "حدد العنصر",
    "mask_object_body": "ارسم على العنصر المراد استبداله فقط. ستُحفظ باقي الصورة.",
    "mask_object_disabled": "حدد العنصر للمتابعة",
    "mask_object_description": "العنصر المراد استبداله",
    "mask_object_empty_title": "غطِّ العنصر المراد استبداله",
    "mask_object_empty_body": "استخدم الفرشاة لتغطية العنصر، ثم الممحاة لتحسين الحواف.",
    "mask_required_floor": "القناع مطلوب: حدد الأرضية قبل المتابعة.",
    "mask_required_wall": "القناع مطلوب: حدد الجدران أو الأسطح قبل المتابعة.",
    "mask_add": "إضافة إلى القناع",
    "mask_remove": "إزالة من القناع",
    "mask_mark": "تحديد",
    "mask_brush": "فرشاة",
    "mask_eraser": "ممحاة",
    "a11y_mask_brush_add": "الفرشاة: إضافة إلى القناع",
    "a11y_mask_eraser_remove": "الممحاة: إزالة من القناع",
    "a11y_undo_mask_stroke": "التراجع عن آخر ضربة قناع",
    "a11y_redo_mask_stroke": "إعادة آخر ضربة قناع",
    "undo": "تراجع",
    "redo": "إعادة",
    "clear": "مسح",
    "clear_mask": "مسح القناع",
    "clear_full_mask": "مسح القناع بالكامل",
    "brush_size": "حجم الفرشاة",
    "precise": "دقيق",
    "wide": "واسع",
    "auto_detect_floor": "كشف الأرضية تلقائياً",
    "auto_detect_wall": "كشف الجدار تلقائياً",
    "layout_plan_title": "خطط التخطيط",
    "layout_plan_body": "حسّن المواضع والحركة ومناطق الاستخدام دون تحويل نمط الغرفة.",
    "layout_generate": "إنشاء التخطيط",
    "layout_select_goal_to_generate": "اختر هدفاً",
    "room_photo": "صورة الغرفة",
    "room_photo_layout_body": "الأساس المستخدم للتخطيط الذكي.",
    "planning_goals": "أهداف التخطيط",
    "constraints": "القيود",
    "constraints_placeholder": "مثال: الحفاظ على ممر بعرض 90 سم، لا تسد النافذة",
    "furniture_to_keep": "الأثاث المراد الإبقاء عليه",
    "furniture_to_keep_placeholder": "مثال: أريكة، طاولة قهوة، وحدة تلفاز",
    "furniture_to_remove": "الأثاث المراد إزالته",
    "furniture_to_remove_placeholder": "مثال: كرسي إضافي، رف مكسور، فوضى",
    "furniture_to_move": "الأثاث المراد نقله",
    "furniture_to_move_placeholder": "مثال: كرسي مريح، مكتب، رف",
    "people_count": "عدد الأشخاص",
    "people_count_placeholder": "مثال: 2 بالغين، 1 طفل",
    "custom_notes": "ملاحظات مخصصة",
    "custom_notes_placeholder": "مثال: أضف زاوية قراءة واترك الباب واضحاً",
    "optional_notes": "ملاحظات اختيارية",
    "optional_notes_placeholder": "مثال: أضف زاوية قراءة واترك الباب واضحاً",
    "add_details_title": "أضف تفاصيل",
    "add_details_body": "حدد قيوداً لتحسين المساحة دون فقدان أولوياتك.",
    "room_type": "نوع الغرفة",
    "important_constraints": "قيود مهمة",
    "important_constraints_placeholder": "مثال: الحفاظ على الأريكة، إضافة مكتب، تحسين الحركة",
    "describe_vision_label": "صف رؤيتك",
    "describe_vision_placeholder": "اختياري: ملمس أو مادة أو أجواء.",
    "design_brief": "ملخص التصميم",
    "space_to_choose": "المساحة المراد اختيارها",
    "style_to_choose": "النمط المراد اختياره",
    "design_pair_format": "%1$s / %2$s",
    "palette_to_choose": "اللوحة المراد اختيارها",
    "replacement_suggestions": "اقتراحات الاستبدال",
    "material_library": "مكتبة المواد",
    "material_library_wall_scope": "الجدار فقط",
    "material_library_floor_scope": "الأرضية فقط",
    "material_selected_wall_preview": "معاينة محددة لمنطقة الجدار المحددة بالقناع فقط.",
    "material_selected_floor_preview": "معاينة محددة لمنطقة الأرضية المحددة بالقناع فقط.",
    "transfer_options": "خيارات النقل",
    "replacement_object": "عنصر الاستبدال",
    "prompt_paint": "اختياري: أضف تفاصيل تشطيب الجدار فقط",
    "prompt_floor": "اختياري: أضف تفاصيل تشطيب الأرضية فقط",
    "prompt_replace": "مثال: أريكة بيج حديثة، بنفس الحجم والإضاءة كالغرفة",
    "prompt_optional": "أضف تعليمة اختيارية",
    "replacement_summary": "ملخص الاستبدال",
    "mask_ready": "القناع جاهز: %1$s",
    "yes": "نعم",
    "to_complete": "لإتمام",
    "describe_new_object": "صف العنصر الجديد المراد إنشاؤه.",
    "choose_replacement_before_generate": "اختر الاستبدال",
    "replacement_prompt_required_error": "اختر أو صف عنصر الاستبدال قبل الإنشاء.",
    "replacement_confirmation_title": "جاهز عند اكتمال الخطوتين",
    "replacement_confirmation_mask_ready": "العنصر المحدد جاهز للاستبدال.",
    "replacement_confirmation_need_mask": "حدد العنصر المراد استبداله.",
    "replacement_confirmation_need_replacement": "اختر اقتراحاً أو صِف العنصر الجديد.",
    "replacement_confirmation_object_format": "العنصر الجديد: %1$s",
    "replacement_result_title": "تم الاستبدال",
    "replacement_result_body": "تستخدم الصورة المنشأة قناعك لتغيير العنصر المحدد فقط مع الحفاظ على الصورة المحيطة سليمة.",
    "replacement_result_mask_used": "القناع",
    "replacement_result_object": "عنصر الاستبدال",
    "replacement_result_status": "حالة النتيجة",
    "paint_mask_before_generate_floor": "قناع الأرضية مطلوب",
    "paint_mask_before_generate_replace": "حدد العنصر قبل الإنشاء",
    "paint_mask_before_generate_wall": "قناع الجدار مطلوب",
    "add_both_images": "أضف الصورتين",
    "upload_photo_of": "ارفع صورة لـ %1$s",
    "add_photo_to_continue": "أضف صورة للمتابعة.",
    "validation_add_source_photo": "أضف صورة أصل للمتابعة.",
    "validation_upload_source_photo": "ارفع صورة أصل من المعرض أو الكاميرا للمتابعة.",
    "validation_choose_option_to_continue": "اختر خياراً واحداً على الأقل للمتابعة.",
    "validation_choose_palette_to_generate": "اختر تناغم ألوان لتفعيل الإنشاء.",
    "validation_select_layout_goal": "اختر هدف تخطيط واحداً على الأقل لتفعيل الإنشاء.",
    "validation_mark_floor_to_generate": "حدد مساحة الأرضية قبل الإنشاء.",
    "validation_mark_object_to_generate": "حدد العنصر المراد استبداله قبل الإنشاء.",
    "validation_mark_wall_to_generate": "حدد الجدران أو الأسطح قبل الإنشاء.",
    "validation_choose_transfer_strength": "اختر شدة النقل قبل الإنشاء.",
    "validation_choose_color_or_prompt": "اختر مادة جدار أو صف تشطيب الجدار قبل الإنشاء.",
    "validation_choose_material_or_prompt": "اختر مادة أرضية أو صف الأرضية قبل الإنشاء.",
    "source_photo_preview": "الصورة الأصلية",
    "source_photo_preview_body": "هذه الصورة التي سيُطبق عليها الاختيار التالي.",
    "mask_preview_title": "معاينة المنطقة المحددة",
    "mask_preview_body": "سيتم تغيير هذه المنطقة المحددة فقط عند الإنشاء.",
    "reference_preview_title": "معاينة النقل",
    "processing_transform": "جارٍ تحضير التحول...",
    "generation_progress_badge": "تشغيل استوديو الذكاء الاصطناعي",
    "generation_progress_title": "جارٍ إنشاء تصميمك",
    "generation_progress_body": "اترك هذه الشاشة مفتوحة أثناء تحضير التصيير.",
    "generation_step_analyzing_room": "تحليل الغرفة",
    "generation_step_applying_style": "تطبيق النمط",
    "generation_step_preparing_result": "تحضير النتيجة",
    "generation_step_finalizing": "الإتمام",
    "layout_changes": "تغييرات التخطيط",
    "layout_suggestions": "اقتراحات التخطيط",
    "layout_summary_format": "تنظم الصورة المنشأة الغرفة حول %1$s. تحافظ على %2$s، تزيل %3$s، تعيد تموضع %4$s، تأخذ في الاعتبار %5$s، وتحترم %6$s دون تغيير نمط الغرفة العام.",
    "layout_default_goals": "أهداف الحركة والاستخدام",
    "layout_default_keep": "العناصر الثابتة والأثاث المهم",
    "layout_default_remove": "الأشياء غير الضرورية أو القطع المعيقة",
    "layout_default_move": "الأثاث سهل النقل",
    "layout_default_people": "القاطنين المحددين",
    "layout_default_constraints": "الممرات والفتحات والقيود المرئية",
    "layout_suggestion_constraints": "تحقق من القياسات الفعلية حول القيود المحددة قبل نقل الأثاث.",
    "layout_suggestion_keep": "احتفظ بالأثاث ذي الأولوية كمرجع، ثم عدّل القطع الثانوية حوله.",
    "layout_suggestion_remove": "أزل العناصر المحددة للإزالة قبل اختبار مسار الحركة الجديد.",
    "layout_suggestion_move": "اختبر أولاً نقل الأثاث المتحرك لتأكيد الحركة قبل أي شراء جديد.",
    "layout_suggestion_people": "حافظ على مناطق الحركة المناسبة للعدد المتوقع اليومي من الأشخاص.",
    "layout_suggestion_openings": "اترك الفتحات والنوافذ والأبواب واضحة للحفاظ على الحركة الطبيعية.",
    "layout_suggestion_vertical_storage": "استخدم الجدران الفارغة للتخزين العمودي إذا كان الهدف هو تحرير الأرضية.",
    "your_result": "نتيجتك",
    "result_saved_workspace": "يُحفظ إنشاؤك الناجح في سجل الملف الشخصي. راجعه بوضوح وقارنه، ثم احفظه أو شاركه أو حمّله أو أعد إنشاءه.",
    "result_replace_body": "يُحفظ استبدالك الناجح في سجل الملف الشخصي. راجع التعديل المحدد بوضوح وقارنه، ثم احفظه أو شاركه أو حمّله أو أعد إنشاءه.",
    "result_empty_title": "لا توجد نتيجة بعد",
    "result_empty_body": "ابدئ إنشاءً وسيظهر صورتك المكتملة هنا مع الخطوات التالية.",
    "result_failed_title": "لم نتمكن من إتمام هذا التصميم",
    "result_contains_title": "ما在里面",
    "result_contains_default": "مفهوم منشأ لـ %1$s بتنسيق %2$s، جاهز للمقارنة مع صورتك الأصلية.",
    "result_contains_layout": "مفهوم تخطيط يركز على %1$s، مع وضع الأثاث وأفكار الحركة مرئية في التصيير.",
    "result_contains_replace": "استبدال عنصر محدد باستخدام %1$s مع الحفاظ على الصورة المحيطة سليمة.",
    "result_contains_reference": "نقل نمط مرجعي باستخدام إشارات %1$s من صورتك المرجعية مع الحفاظ على الغرفة الأصلية.",
    "result_contains_paint": "مفهوم طلاء وتشطيب جدران باستخدام %1$s على الأسطح المحددة.",
    "result_contains_floor": "مفهوم أرضية باستخدام %1$s على مساحة الأرضية المحددة.",
    "result_contains_failed": "لم يكتمل الإنشاء، لذا لم تُحفظ صورة مكتملة. يمكنك إعادة الإنشاء عند الجاهزية.",
    "result_saved_to_profile_history": "محفوظ في سجل الملف الشخصي.",
    "new_creation": "إنشاء جديد",
    "generated_image": "صورة منشأة",
    "generated_result": "نتيجة منشأة",
    "original_image": "الصورة الأصلية",
    "view_original": "عرض الأصل",
    "reference_result_images": "الأصل والمرجع والنتيجة",
    "before_after": "قبل / بعد",
    "before_after_slider": "شريط قبل / بعد",
    "before_after_slider_hint": "حرّك الشريط لكشف الصورة الأصلية فوق النتيجة المنشأة.",
    "before": "قبل",
    "after": "بعد",
    "reference": "مرجع",
    "metadata": "البيانات الوصفية",
    "metadata_service": "الخدمة: %1$s",
    "metadata_style": "النمط: %1$s",
    "metadata_prompt": "ال_prompt: %1$s",
    "metadata_replacement_object": "عنصر الاستبدال: %1$s",
    "metadata_mask": "القناع: %1$s",
    "metadata_status": "الحالة: %1$s",
    "metadata_date": "التاريخ: %1$s",
    "ai_choice": "اختيار الذكاء الاصطناعي",
    "no_custom_prompt": "بدون تعليمة مخصصة",
    "save": "حفظ",
    "create": "إنشاء",
    "share": "مشاركة",
    "download": "تنزيل",
    "retry": "إعادة المحاولة",
    "regenerate": "إعادة الإنشاء",
    "toast_design_saved": "تم حفظ التصميم في محفظة الملف الشخصي والسجل.",
    "toast_design_downloaded": "تم تنزيل التصميم في معرض جهازك.",
    "toast_design_save_failed": "تعذر حفظ هذا التصميم.",
    "toast_added_to_project": "تم الحفظ في مساحة عمل المشروع.",
    "toast_project_save_failed": "تعذر تحديث هذا المشروع.",
    "toast_favorite_added": "تمت الإضافة إلى المفضلة.",
    "toast_favorite_removed": "تمت الإزالة من المفضلة.",
    "toast_moodboard_added": "تمت الإضافة إلى لوحة الأجواء.",
    "toast_moodboard_removed": "تمت الإزالة من لوحة الأجواء.",
    "toast_share_failed": "تعذر مشاركة هذا التصميم الآن.",
    "share_design_chooser": "مشاركة التصميم",
    "try_another_style": "جرّب نمطاً آخر",
    "undo_edit_design_choices": "تراجع / تعديل خيارات التصميم",
    "auth_open_failed": "تعذر فتح صفحة تسجيل الدخول الآن.",
    "reference_missing_error": "أضف صورة الغرفة والصورة المرجعية قبل الإنشاء.",
    "layout_goal_required_error": "اختر هدف تخطيط واحداً على الأقل قبل الإنشاء.",
    "no_diamonds_error_token": "لا توجد ماسات متبقية.",
    "prepare_example_failed": "تعذر تحضير صورة المثال.",
    "prepare_reference_failed": "تعذر تحضير الصورة المرجعية.",
    "real_mask_required_error": "مطلوب منطقة محددة حقيقية.",
    "read_selected_image_failed": "تعذر قراءة الصورة المحددة.",
    "mark_area_before_generate": "حدد المنطقة قبل الإنشاء.",
    "ai_generation_unavailable": "إنشاء الذكاء الاصطناعي غير متاح الآن.",
    "no_diamonds_recharge": "لا توجد ماسات متبقية. أعد الشحن للمتابعة.",
    "image_prepare_failed": "تعذر تحضير هذه الصورة.",
    "design_processing_delayed": "التصميم لا يزال قيد المعالجة. حاول مرة أخرى بعد قليل.",
    "generation_failed_retry": "فشل الإنشاء. حاول مرة أخرى.",
    "image_loading_title": "جارٍ تحضير الصورة",
    "image_loading_body": "التصيير الخاص بك قيد التحميل الآن.",
    "image_unavailable_title": "الصورة غير متاحة",
    "image_unavailable_body": "تعذر تحميل هذه الصورة الآن.",
    "error_offline_retry": "يبدو أنك غير متصل بالإنترنت. تحقق من اتصالك وأعد المحاولة.",
    "error_timeout_retry": "يستغرق هذا وقتاً أطول من المتوقع. أعد المحاولة بعد قليل.",
    "discover_cluster_interiors": "التصميم الداخلي",
    "discover_cluster_architecture": "التصميم الخارجي",
    "discover_cluster_landscapes": "الحديقة",
    "discover_hero_body": "إلهام جاهز للتحويل إلى إبداع",
    "see_all": "عرض الكل",
    "ideas_count": "%1$d أفكار",
    "discover_detail_subtitle": "اضغط على صورة لمعاينتها",
    "create_with_style": "استخدم هذا النمط",
    "preview": "معاينة",
    "gallery_numbered_title": "%1$s %2$d",
    "category_spaces": "المساحات",
    "category_tools": "الأدوات",
    "category_kitchen": "المطبخ",
    "category_living_room": "غرفة المعيشة",
    "category_bedroom": "غرفة النوم",
    "category_bathroom": "الحمام",
    "category_dining_room": "غرفة الطعام",
    "category_office": "المكتب",
    "category_library": "المكتبة",
    "category_entry": "المدخل",
    "category_leisure": "الترفيه",
    "category_service": "الخدمة",
    "category_villa": "فيلا",
    "category_apartment": "شقة",
    "category_residential": "سكني",
    "category_garden": "الحديقة",
    "category_floor": "الأرضية",
    "category_wall": "الجدار",
    "elite_sync": "مزامنة...",
    "elite_syncing": "جارٍ المزامنة...",
    "elite_sync_ok": "تمت المزامنة",
    "elite_local": "محلي",
    "elite_resync": "إعادة المزامنة",
    "elite_pass_sync_initial": "جارٍ مزامنة المكافآت اليومية...",
    "elite_pass_synced": "تمت مزامنة المكافآت اليومية.",
    "elite_pass_local_sync": "تبقى المكافآت اليومية متاحة محلياً حتى تعود المزامنة.",
    "today": "اليوم",
    "claimed": "تم المطالبة",
    "available": "متاح",
    "locked": "مقفل",
    "streak": "السلسلة",
    "daily_reward": "المكافأة اليومية",
    "daily_reward_title": "المكافأة اليومية",
    "daily_reward_subtitle": "+1 ماسة، متاح مرة واحدة يومياً.",
    "daily_reward_day_format": "اليوم %1$d",
    "daily_reward_streak_format": "سلسلة %1$d أيام",
    "daily_reward_soft_start": "بداية جديدة",
    "daily_reward_claim": "المطالبة",
    "daily_reward_claimed": "تم المطالبة",
    "elite_intro": "مطالبة بـ 1 ماسة يومياً. في اليوم السابع، احصل على 3 ماسات و24 ساعة Pro بعد تأكيد المكافأة.",
    "elite_footer_syncing": "جارٍ مزامنة المكافآت اليومية...",
    "elite_footer_day7_confirmed": "تم تأكيد مكافأة اليوم السابع. Pro مفعّل.",
    "elite_footer_reward_confirmed": "تم تأكيد الماسة اليومية.",
    "elite_footer_day7_available": "مكافأة اليوم السابع جاهزة: 3 ماسات و24 ساعة Pro.",
    "elite_footer_diamond_available": "الماسة اليومية جاهزة.",
    "elite_footer_balance_full": "الرصيد اليومي ممتلئ.",
    "elite_footer_next_window": "المكافأة التالية تُفتح في النافذة التالية.",
    "next_window": "النافذة التالية",
    "not_ready": "غير جاهز",
    "reward_syncing": "جارٍ مزامنة المكافأة...",
    "reward_day7_synced": "تمت مزامنة مكافأة اليوم السابع.",
    "reward_synced": "تمت مزامنة المكافأة.",
    "reward_already_claimed": "تم المطالبة بالمكافأة اليوم بالفعل.",
    "reward_claim_unconfirmed": "تعذر تأكيد هذه المكافأة الآن.",
    "claim_today": "تم المطالبة اليوم",
    "daily_balance_full": "الرصيد اليومي ممتلئ",
    "claim_d7_pro": "المطالبة بمكافأة اليوم السابع Pro",
    "claim_diamond": "المطالبة بالماسة",
    "retry_sync_reward": "إعادة مزامنة المكافأة",
    "sync_required": "المزامنة مطلوبة",
    "next_reward_pending": "المكافأة التالية معلّقة",
    "locked_today": "المكافأة التالية معلّقة",
    "open_diamond_store": "فتح متجر الماسات",
    "a11y_open_diamond_store_balance": "فتح متجر الماسات. %1$s",
    "day_7_pro": "مكافأة اليوم السابع Pro",
    "unlock_unlimited_designs": "افتح تصاميم غير محدودة",
    "feature_priority_ai": "معالجة ذكاء اصطناعي ذات أولوية",
    "feature_clean_exports": "تصدير نظيف بجودة عالية",
    "feature_frictionless_generations": "إنشاءات سلسة",
    "profile_personal_space": "المساحة الشخصية",
    "profile_photo_preview": "معاينة صورة الملف الشخصي",
    "profile_sign_in_sync": "سجّل الدخول لمزامنة إبداعاتك ومشترياتك.",
    "profile_signed_in_sync": "تم تسجيل الدخول. يمكن مزامنة الإبداعات والماسات والمشتريات.",
    "signed_out": "تم تسجيل الخروج",
    "diamonds_count": "%1$d ماسة",
    "active_pro": "Pro مفعّل",
    "free_plan": "الخطة المجانية",
    "sign_in": "تسجيل الدخول",
    "sign_up": "التسجيل",
    "your_design": "تصميمك",
    "rate_this_result": "قيّم هذه النتيجة",
    "like": "إعجاب",
    "dislike": "عدم إعجاب",
    "room_label": "الغرفة",
    "style_label": "النمط",
    "delete_image": "حذف الصورة",
    "no_designs_yet": "لا توجد تصاميم بعد",
    "no_designs_body": "أنشئ تصميمك الأول وسيظهر هنا.",
    "diamonds": "الماسات",
    "connection_state": "حالة الاتصال",
    "account_connected": "الحساب متصل",
    "local_session": "جلسة محلية",
    "local_session_with_device": "جلسة محلية على هذا الجهاز. سجّل الدخول لمزامنتها.",
    "local_creations_body": "تبقى الإبداعات متاحة على هذا الجهاز.",
    "connection": "الاتصال",
    "portfolio_history": "المحفظة والسجل",
    "portfolio_saved_count": "%1$d إبداع محفوظ",
    "history_timeline": "الجدول الزمني للسجل",
    "history_saved_count": "%1$d صورة منشأة محفوظة محلياً",
    "history_today": "اليوم",
    "history_yesterday": "أمس",
    "history_this_week": "هذا الأسبوع",
    "history_older": "أقدم",
    "history_style_budget_unavailable": "النمط أو الميزانية غير محددة",
    "history_open_failed": "تعذر فتح عنصر السجل هذا.",
    "history_favorited": "تمت الإضافة إلى المفضلة.",
    "history_unfavorited": "تمت الإزالة من المفضلة.",
    "history_saved_to_project": "تم الحفظ في %1$s.",
    "history_deleted": "تم حذف عنصر السجل.",
    "delete_history_item_title": "حذف هذه الصورة؟",
    "delete_history_item_body": "يزيل هذه الصورة المنشأة من السجل المحلي والمفضلة ولوحات المشاريع على هذا الجهاز.",
    "project": "المشروع",
    "delete": "حذف",
    "room_projects": "مشاريع الغرف",
    "room_projects_body": "نظّم الأصليات والإبداعات والمفضلة والملاحظات واتجاه النمط في مساحات عمل التصميم.",
    "new_project": "مشروع جديد",
    "project_create_title": "إنشاء مشروع غرفة",
    "project_create_from_result_title": "إنشاء مشروع من النتيجة",
    "project_workspace_title": "مساحة عمل المشروع",
    "project_name": "اسم المشروع",
    "project_name_hint": "غرفتي، تجديد المطبخ...",
    "project_room_hint": "غرفة نوم، مطبخ، حديقة...",
    "project_notes": "ملاحظات",
    "project_notes_hint": "قياسات، قيود، أفكار شراء، أو ملاحظات العميل",
    "project_style_info": "معلومات النمط",
    "project_style_info_hint": "محايد عصري دافئ، Japandi بلوظة، أجواء منتجع حديقة...",
    "project_room_unspecified": "المساحة غير محددة",
    "project_created": "تم الإنشاء %1$s",
    "project_originals_count": "%1$d أصلية",
    "project_results_count": "%1$d نتائج",
    "project_favorites_count": "%1$d مفضلة",
    "project_generated_results": "النتائج المنشأة",
    "project_favorites": "المفضلة",
    "profile_moodboard": "لوحة الأجواء",
    "empty_action_explore_discover": "استكشف اكتشف",
    "empty_action_start_project": "ابدئ مشروعاً",
    "empty_projects_title": "ابدئ مساحة عمل غرفة",
    "empty_projects_body": "معاينة لوحات المشاريع لأفكار غرفة النوم أو المطبخ أو الحديقة، ثم ابدأ مشروعاً للغرفة التي تريد تحسينها.",
    "saved_idea": "فكرة محفوظة",
    "result_workspace_title": "مساحة عمل التصميم",
    "result_workspace_body": "احتفظ بهذا المفهوم مع مشروع ومفضلة وملاحظات لوحة الأجواء.",
    "result_workspace_project": "مرتبط بـ %1$s",
    "save_to_project": "حفظ في المشروع",
    "save_to_project_body": "اختر أين يجب أن تعيش هذه الصورة الأصلية والنتيجة المنشأة.",
    "no_projects_yet": "لا توجد مشاريع بعد. أنشئ واحداً من هذه النتيجة.",
    "favorite": "المفضلة",
    "favorited": "تمت الإضافة للمفضلة",
    "add_to_moodboard": "إضافة إلى لوحة الأجواء",
    "profile_tab_count": "%1$s %2$d",
    "profile_tab_favorites": "المفضلة",
    "profile_tab_moodboard": "لوحة الأجواء",
    "profile_tab_history": "السجل",
    "profile_tab_projects": "المشاريع",
    "profile_favorites_title": "المفضلة",
    "profile_favorites_body": "النتائج المنشأة وأفكار اكتشف التي تُحدّدها محفوظة محلياً على هذا الجهاز.",
    "profile_moodboard_title": "لوحة أجواء النمط",
    "profile_moodboard_body": "اجمع أنماط اكتشف والصور المرجعية والألوان والمفاهيم المنشأة لتوجيه غرفتك القادم.",
    "empty_favorites_title": "ابدئ بحفظ المفضلة",
    "empty_favorites_body": "استخدم عينات الحفظ أدناه كدليل، ثم نجم أفكار اكتشف أو النتائج المنشأة التي تريد الاحتفاظ بها.",
    "empty_moodboard_title": "أنشئ لوحة أجواء نمطية",
    "empty_moodboard_body": "اجمع الملمس واللوحات ومفاهيم الغرف في لوحة بصرية قبل إنشاء الاتجاه القادم.",
    "empty_history_title": "سجلك جاهز لأول تصميم",
    "empty_history_body": "ستظهر الإنشاءات المكتملة هنا مع إجراءات سريعة للفتح أو المفضلة أو الحفظ في المشروع أو الحذف.",
    "saved_discover_source": "اكتشف / %1$s",
    "saved_generated_source": "النتيجة المنشأة محفوظة محلياً",
    "saved_local_source": "محفوظ محلياً على هذا الجهاز",
    "sample_favorite_modern_title": "صالة عصرية دافئة",
    "sample_favorite_modern_subtitle": "مثال مفضل",
    "sample_favorite_garden_title": "توهج الفناء",
    "sample_favorite_garden_subtitle": "فكرة حديقة",
    "sample_favorite_floor_title": "مزاج أرضية بلوظة",
    "sample_favorite_floor_subtitle": "حفظ مادة",
    "sample_moodboard_japandi_title": "Japandi هادئ",
    "sample_moodboard_japandi_subtitle": "بطاقة نمط",
    "sample_moodboard_palette_title": "لوحة أخضر الشبت",
    "sample_moodboard_palette_subtitle": "اتجاه اللون",
    "sample_moodboard_exterior_title": "واجهة فيلا",
    "sample_moodboard_exterior_subtitle": "معلم معماري",
    "sample_project_bedroom_title": "غرفة النوم الرئيسية",
    "sample_project_bedroom_subtitle": "مثال مشروع",
    "sample_project_kitchen_title": "تجديد المطبخ",
    "sample_project_kitchen_subtitle": "مثال مشروع",
    "sample_project_garden_title": "مفهوم الحديقة",
    "sample_project_garden_subtitle": "مثال مشروع",
    "sample_history_before_after_title": "تجديد فاخر",
    "sample_history_before_after_subtitle": "قبل / بعد جاهز",
    "sample_history_layout_title": "تخطيط مركّز",
    "sample_history_layout_subtitle": "مثال تخطيط",
    "sample_history_reference_title": "نقل عصري",
    "sample_history_reference_subtitle": "مثال مرجعي",
    "purchases": "المشتريات",
    "credits_available": "%1$d رصيد متاح",
    "active_pro_access": "وصول Pro مفعّل",
    "clean_exports_and_generations": "تصدير نظيف وإنشاءات سلسة",
    "store": "المتجر",
    "manage": "إدارة",
    "view": "عرض",
    "settings": "الإعدادات",
    "preferences": "التفضيلات",
    "preferences_subtitle": "اللغة والمساعدة والخصوصية والحساب",
    "open": "فتح",
    "share_app": "مشاركة التطبيق",
    "share_app_subtitle": "ادعُ شخصاً لتجربة HomeDecor AI",
    "rate_us": "قيّمنا",
    "rate_us_subtitle": "قيّمنا على Play Store",
    "version_label": "الإصدار %1$s",
    "share_app_text": "جرّب HomeDecor AI لتحويل مساحاتك بالذكاء الاصطناعي.",
    "share_app_long_text": "جرّب HomeDecor AI لتحويل التصميمات الداخلية والخارجية والحدائق والجدران والأرضيات.",
    "share_app_share_text": "جرّب HomeDecor AI لتحويل التصميمات الداخلية والخارجية والحدائق والجدران والأرضيات: %1$s",
    "share_app_chooser": "مشاركة HomeDecor AI",
    "cancel": "إلغاء",
    "empty_portfolio_title": "لا توجد إبداعات محفوظة",
    "empty_portfolio_body": "ستظهر مفاهيمك المنشأة هنا مع أدواتها ونمطها وصورتها النهائية.",
    "create_design": "أنشئ تصميماً",
    "paywall_title": "الترقية إلى Pro",
    "paywall_subtitle": "أنشئ أسرع وصدّر بوضوح واحتفظ بمفاهيمك المميزة بسلاسة.",
    "paywall_eyebrow": "استوديو PRO",
    "paywall_pro_studio_title": "استوديو Pro لمشاريعك الداخلية.",
    "paywall_pro_studio_subtitle": "مفاهيم 4K غير محدودة، تصدير نظيف، وتصيير أسرع لأعمال HomeDecor AI الجاهزة للعرض.",
    "paywall_outcome_4k_title": "تصييرات 4K غير محدودة",
    "paywall_outcome_4k_body": "كرر بحرية مفاهيم الغرف والتنويعات الجاهزة للعملاء.",
    "paywall_outcome_watermark_title": "تصدير بدون علامة مائية",
    "paywall_outcome_watermark_body": "احفظ صوراً مصقولة للمشاركة والعرض التقديمي والمحفظة.",
    "paywall_outcome_priority_title": "تصيير بأولوية",
    "paywall_outcome_priority_body": "تحرّك أسرع أثناء استكشاف الأنماط والتخطيطات والجدران والأرضيات.",
    "paywall_included": "مشمول",
    "paywall_google_play_checkout": "دفع آمن عبر Google Play. يمكنك الإلغاء في أي وقت.",
    "weekly": "أسبوعي",
    "paywall_access_weekly": "وصول أسبوعي",
    "paywall_access_monthly": "وصول شهري",
    "paywall_access_yearly": "وصول سنوي",
    "paywall_billed_weekly": "فوترة أسبوعية",
    "paywall_billed_monthly": "فوترة شهرية",
    "paywall_billed_yearly": "%1$s فقط سنوياً",
    "paywall_flexible_access": "وصول Pro مرن",
    "paywall_best_offer": "أفضل عرض",
    "paywall_start_trial": "ابدأ Pro",
    "paywall_cta_fine_print": "سعرك الدقيق وشروط التجديد تؤكد عليها Google Play قبل الشراء.",
    "paywall_restore_or_retry": "أعد المحاولة بعد قليل أو استعد اشتراكاً قائماً.",
    "paywall_diamond_store_title": "متجر الماسات",
    "paywall_diamond_store_subtitle": "اشترِ رصيد إنشاء بدون اشتراك",
    "premium_creation": "إبداع مميز",
    "paywall_feature_generations": "إنشاءات غير محدودة أو حد أقصى شهري أعلى",
    "paywall_feature_fast": "تصيير أسرع",
    "paywall_feature_styles": "أنماط مميزة",
    "paywall_feature_history": "سجل كامل",
    "paywall_feature_watermark": "بدون علامة مائية عند التوفر",
    "loading_prices": "جارٍ تحميل الأسعار...",
    "monthly": "شهري",
    "yearly": "سنوي",
    "pro_activated": "تم تفعيل Pro",
    "continue_yearly": "المتابعة بالخطة السنوية",
    "continue_monthly": "المتابعة بالخطة الشهرية",
    "prices_unavailable": "الأسعار غير متاحة",
    "restore_purchases": "استعادة المشتريات",
    "restoring": "جارٍ الاستعادة...",
    "buy_diamonds_only": "شراء ماسات فقط",
    "subscriptions_unavailable": "الاشتراكات غير متاحة مؤقتاً.",
    "no_subscription_available": "لا يوجد اشتراك متاح الآن.",
    "load_prices_failed": "تعذر تحميل الأسعار الآن.",
    "plan_unavailable": "هذه الخطة غير متاحة الآن.",
    "restore_unavailable": "الاستعادة غير متاحة مؤقتاً.",
    "no_active_pro_purchase": "لم يتم العثور على شراء Pro نشط.",
    "restore_failed": "تعذر استعادة المشتريات الآن.",
    "auth_welcome": "مرحباً بعودتك.",
    "auth_subtitle": "سجّل الدخول للعثور على تصاميمك ورويدك وسجلك.",
    "auth_welcome_back": "مرحباً بعودتك.",
    "auth_sign_in_subtitle": "سجّل الدخول للعثور على تصاميمك ورويدك وسجلك.",
    "auth_start_creating": "ابدئ الإبداع.",
    "auth_sign_up_subtitle": "أنشئ حسابك وابدئ أول تصيير بالذكاء الاصطناعي مجاناً.",
    "continue_with_google": "المتابعة عبر Google",
    "continue_with_apple": "المتابعة عبر Apple",
    "google_initial": "G",
    "google_account_name": "حساب Google",
    "google_account_email": "homedecor.user@gmail.com",
    "or": "أو",
    "email": "البريد الإلكتروني",
    "password": "كلمة المرور",
    "full_name": "الاسم الكامل",
    "confirm_password": "تأكيد كلمة المرور",
    "forgot_password": "نسيت كلمة المرور؟",
    "create_account": "إنشاء حساب",
    "auth_data_protected": "بياناتك محمية ولا تُشارك أبداً.",
    "auth_free_to_start": "مجاني للبدء، لا حاجة لبطاقة ائتمان.",
    "no_account_yet": "ليس لديك حساب بعد؟",
    "already_have_account": "لديك حساب بالفعل؟",
    "sign_in_button": "تسجيل الدخول",
    "toggle_password_visibility": "إظهار/إخفاء كلمة المرور",
    "auth_real_flow_note": "يفتح صفحة تسجيل الدخول الآمنة لـ HomeDecor AI. لن يُعلم التطبيق بتسجيل دخولك حتى تتوفر جلسة حقيقية.",
    "language": "اللغة",
    "language_current": "العربية",
    "language_picker_title": "اختر اللغة",
    "toast_language_selected": "تم تحديد العربية.",
    "feedback": "اكتب لنا / الملاحظات",
    "feedback_subtitle": "أرسل اقتراحاً للفريق",
    "feedback_dialog_title": "إرسال ملاحظات",
    "feedback_hint": "أخبرنا بما نجح أو ما تعطل أو ما تريده بعد ذلك.",
    "feedback_send": "إرسال",
    "feedback_sending": "جارٍ الإرسال...",
    "feedback_empty_error": "أضف تفاصيل أكثر قبل الإرسال.",
    "feedback_sent": "شكراً. تم إرسال ملاحظاتك.",
    "feedback_failed": "تعذر إرسال الملاحظات الآن.",
    "faq": "الأسئلة الشائعة",
    "faq_subtitle": "أسئلة شائعة حول تصاميم الذكاء الاصطناعي",
    "faq_toast": "الأسئلة الشائعة: استورد صورة، اختر خياراتك، ثم أنشئ مفهوماً.",
    "restore_purchases_subtitle": "استعادة مشتريات Pro النشطة من Google Play",
    "restore_unavailable_body": "استعادة المشتريات غير متاحة مؤقتاً في هذا الإصدار. مشترياتك من Google Play آمنة ويمكن استعادتها عند توفر خدمات المتجر.",
    "restore_purchases_toast": "المشتريات المؤكدة من Google Play تتم مزامنتها تلقائياً.",
    "diamond_store": "متجر الماسات",
    "diamond_store_subtitle": "شراء رصيد الإنشاء",
    "terms": "الشروط والأحكام",
    "terms_subtitle": "قواعد الاستخدام وإخلاء المسؤولية",
    "privacy_policy": "سياسة الخصوصية",
    "privacy_subtitle": "البيانات والصور وحساب المستخدم",
    "delete_information": "حذف المعلومات",
    "delete_account": "حذف الحساب",
    "delete_account_subtitle": "طلب حذف الحساب",
    "delete_account_title": "حذف بيانات الحساب؟",
    "delete_account_body": "يزيل هذا نهائياً تصاميمك ومشاريعك وملاحظاتك وبيانات حسابك المحلي من HomeDecor AI.",
    "delete_account_confirm": "حذف البيانات",
    "deleting_account": "جارٍ الحذف...",
    "delete_account_done": "تم حذف بيانات الحساب. جلسة محلية جديدة جاهزة.",
    "delete_account_failed": "تعذر حذف بيانات الحساب الآن.",
    "log_out": "تسجيل الخروج",
    "logout_subtitle": "إنهاء جلسة الحساب الحالية",
    "logout_title": "تسجيل الخروج؟",
    "logout_body": "يمكنك تسجيل الدخول مرة أخرى في أي وقت. الإبداعات المحلية على هذا الجهاز ستبقى متاحة.",
    "logout_confirm": "تسجيل الخروج",
    "logout_done": "تم تسجيل خروجك.",
    "sign_in_subtitle": "فتح صفحة تسجيل الدخول الآمنة",
    "settings_temporarily_unavailable_title": "غير متاح مؤقتاً",
    "settings_temporarily_unavailable_body": "هذا الإعداد غير متاح مؤقتاً. يرجى المحاولة مرة أخرى بعد قليل.",
    "settings_action_in_progress": "يرجى الانتظار حتى تنتهي إجراء الإعدادات الحالي.",
    "open_link_failed": "تعذر فتح هذا الرابط الآن.",
    "store_purchases_unavailable": "المشتريات غير متاحة مؤقتاً.",
    "store_no_packs": "لا توجد حزم متاحة الآن.",
    "store_load_packs_failed": "تعذر تحميل الحزم الآن.",
    "store_offline_retry": "أنت غير متصل. أعد الاتصال لتحميل المشتريات.",
    "store_timeout_retry": "المتجر يستغرق وقتاً طويلاً للرد. أعد المحاولة بعد قليل.",
    "store_some_packs_unavailable": "بعض الحزم غير متاحة حتى يتم إصلاح تعيينها في Google Play.",
    "pack_unavailable_google": "الحزمة غير متاحة في Google Play الآن.",
    "pack_not_available_in_store": "غير متاح في المتجر",
    "purchase_google_confirmed": "تم تأكيد شراء Google Play. جارٍ مزامنة الماسات...",
    "purchase_cancelled": "تم إلغاء الشراء.",
    "purchase_failed": "فشل الشراء. حاول مرة أخرى.",
    "purchase_offline_retry": "أنت غير متصل. أعد الاتصال قبل إعادة محاولة الشراء.",
    "purchase_timeout_retry": "استغرق الشراء وقتاً طويلاً للرد. حاول مرة أخرى بعد قليل.",
    "current_balance": "الرصيد الحالي",
    "get_more_credits": "احصل على المزيد من الرصيد",
    "loading_packs": "جارٍ تحميل الحزم...",
    "pack_title": "حزمة %1$s",
    "purchase_confirmed": "تم تأكيد الشراء",
    "select_real_pack_google_play": "اختر حزمة حقيقية في Google Play.",
    "purchase_validating": "جارٍ التحقق من الشراء...",
    "diamond_purchase_confirmed": "تمت إضافة الماسات.",
    "diamond_purchase_sync_failed": "تم تأكيد الشراء، لكن تعذر مزامنة الماسات الآن.",
    "pro_syncing": "جارٍ مزامنة وصول Pro...",
    "pro_activated_success": "تم تفعيل وصول Pro.",
    "pro_sync_failed": "تم تأكيد شراء Pro، لكن تعذر مزامنة الوصول الآن.",
    "purchase_sync_offline": "تم تأكيد الشراء. أعد الاتصال لمزامنته بأمان.",
    "purchase_sync_timeout": "تم تأكيد الشراء. المزامنة تستغرق وقتاً أطول من المتوقع؛ أعد المحاولة بعد قليل.",
    "syncing_short": "جارٍ المزامنة...",
    "diamonds_amount": "%1$d ماسة",
    "disclosure_title": "مفاهيم منشأة بالذكاء الاصطناعي",
    "disclosure_body": "ينشئ HomeDecor AI صوراً ملهمة. تحقق دائماً من القياسات والتغييرات الهيكلية والتصاريح والأسعار وتوفر المنتجات قبل البناء أو الشراء.",
    "understood": "أفهم",
    "option_ai_suggestion": "اقتراح الذكاء الاصطناعي",
    "option_room_living_room": "غرفة المعيشة",
    "option_room_bedroom": "غرفة النوم",
    "option_room_kitchen": "المطبخ",
    "option_room_bathroom": "الحمام",
    "option_room_home_office": "المكتب المنزلي",
    "option_room_dining_room": "غرفة الطعام",
    "option_room_child_room": "غرفة الأطفال",
    "option_room_home_cinema": "المسرج المنزلي",
    "option_room_game_room": "غرفة الألعاب",
    "option_room_entry_hall": "المدخل والممر",
    "option_room_library": "المكتبة",
    "option_room_laundry": "غرفة الغسيل",
    "option_building_apartment": "شقة",
    "option_building_house": "منزل",
    "option_building_office": "مبنى مكاتب",
    "option_building_residential": "سكني",
    "option_building_retail": "تجاري",
    "option_building_villa": "فيلا",
    "option_garden_christmas": "عيد الميلاد",
    "option_style_modern": "عصري",
    "option_style_luxury": "فاخر",
    "option_style_japandi": "Japandi",
    "option_style_cyberpunk": "سايبربنك",
    "option_style_tropical": "استوائي",
    "option_style_minimalist": "بسيط",
    "option_style_moroccan": "مغربي",
    "option_style_scandinavian": "اسكندنافي",
    "option_style_bohemian": "بوهيمي",
    "option_style_midcentury": "منتصف القرن",
    "option_style_art_deco": "آرت ديكو",
    "option_style_coastal": "ساحلي",
    "option_style_rustic": "ريفي",
    "option_style_vintage": "كلاسيكي",
    "option_style_mediterranean": "متوسطي",
    "option_style_glam": "لامع",
    "option_style_french_country": "ريف فرنسي",
    "option_mask_wall": "الجدار",
    "option_mask_floor": "الأرضية",
    "option_mask_sofa": "أريكة",
    "option_mask_table": "طاولة",
    "option_mask_cabinet": "خزانة",
    "option_mask_lighting": "الإضاءة",
    "mask_wall_marked": "تم تحديد الجدار",
    "mask_floor_marked": "تم تحديد الأرضية",
    "mask_object_marked": "تم تحديد العنصر",
    "option_floor_light_wood": "أرضية خشب فاتح",
    "option_floor_dark_wood": "أرضية خشب داكن",
    "option_floor_marble": "رخام كرارا",
    "option_material_oak_wood": "خشب بلوظة",
    "option_material_walnut": "خشب جوز",
    "option_material_concrete": "خرسانة",
    "option_material_limewash": "طين извест",
    "option_material_terrazzo": "تيرازو",
    "option_material_white_tile": "بلاط أبيض",
    "option_material_black_tile": "بلاط أسود",
    "option_material_warm_beige_paint": "طلاء بيج دافئ",
    "option_material_dark_elegant_paint": "طلاء داكن أنيق",
    "option_floor_polished_concrete": "خرسانة مصقولة",
    "option_floor_modern_tile": "بلاط عصري",
    "option_floor_natural_stone": "حجر طبيعي",
    "option_floor_premium_vinyl": "فينيل فاخر",
    "option_floor_elegant_carpet": "سجاد أنيق",
    "option_layout_open_flow": "حركة مفتوحة",
    "option_layout_more_storage": "تخزين أكثر",
    "option_layout_office_corner": "زاوية مكتبية",
    "option_layout_family_space": "مساحة عائلية",
    "option_layout_larger_living_room": "غرفة معيشة أوسع",
    "option_layout_better_light": "إضاءة أفضل",
    "option_layout_full_reorg": "إعادة تنظيم كاملة",
    "option_reference_subtle": "خفيف",
    "option_reference_balanced": "متوازن",
    "option_reference_faithful": "وفي",
    "option_reference_very_faithful": "وفي جداً",
    "option_reference_palette_only": "اللوحة فقط",
    "option_reference_materials": "المواد",
    "option_reference_furniture": "الأثاث",
    "option_reference_light": "الإضاءة",
    "option_reference_full_mood": "أجواء كاملة",
    "option_paint_warm_white": "أبيض دافئ",
    "option_paint_beige": "بيج",
    "option_paint_light_gray": "رمادي فاتح",
    "option_paint_sage_green": "أخضر الشبت",
    "option_paint_soft_blue": "أزرق ناعم",
    "option_paint_terracotta": "تيرا كوتا",
    "option_paint_elegant_black": "أسود أنيق",
    "option_replace_sofa": "أريكة بيج عصرية",
    "option_replace_coffee_table": "طاولة قهوة خشب فاتح",
    "option_replace_black_pendant": "إضاءة معلقة سوداء بسيطة",
    "option_replace_potted_plant": "نبات مزروع كبير",
    "option_replace_boucle_armchair": "كرسي مريح كريمي",
    "option_replace_tv_unit": "وحدة تلفاز جوز مبسطة",
    "option_replace_template_sofa": "استبدال الأريكة",
    "option_replace_template_table": "استبدال الطاولة",
    "option_replace_template_lamp": "استبدال المصباح",
    "option_replace_template_rug": "استبدال السجاد",
    "option_replace_template_wall_art": "استبدال لوحة الجدار",
    "option_replace_template_plant": "استبدال النبات",
    "option_replace_template_chair": "استبدال الكرسي",
    "option_replace_template_cabinet": "استبدال الخزانة",
    "option_palette_curated_mix": "مزيج منتقى",
    "option_palette_millennial_gray": "رمادي عصري",
    "option_palette_terracotta_mirage": "سراب التيرا كوتا",
    "option_palette_forest_tones": "ألوان الغابة",
    "option_palette_peach_orchard": "بستان الخوخ",
    "option_palette_fuchsia_bloom": "إزهار الفوشيا",
    "option_palette_emerald_gem": "زمردي",
    "option_palette_pastel_breeze": "نسيم الباستيل",
    "option_palette_ocean_mist": "ضباب المحيط",
    "option_palette_velvet_twilight": "غسق المخمل",
    "option_palette_amethyst_dream": "حلم الجمشت",
    "option_palette_fuchsia_noir": "فوشيا نوار",
    "option_design_preserve": "الحفاظ على التخطيط",
    "option_design_preserve_description": "احتفظ بالجدران والفتحات والأحجام في مكانها مع تحسين النمط.",
    "option_design_free": "تجديد بحرية",
    "option_design_free_description": "اسمح للذكاء الاصطناعي باقتراح تحول أكثر طموحاً وإبداعاً.",
    "pack_starter": "المبتدئ",
    "pack_designer": "المصمم",
    "pack_architect": "المعماري",
    "pack_estate": "الاستوديو",
    "pack_badge_popular": "الأشهر",
    "pack_badge_best_offer": "أفضل عرض",
    "pack_starter_description": "لاختبار عدة أفكار بدون التزام.",
    "pack_designer_description": "أفضل توازن لاستكشاف غرفة كاملة.",
    "pack_architect_description": "مبني لمسلسلات المفاهيم والتنويعات.",
    "pack_estate_description": "رصيد كبير للمشاريع الكبيرة والمحفظات.",
    "ready": "جاهز",
    "failed": "فشل",
    "category_landscape": "المناظر الطبيعية",
    "option_outdoor_backyard": "الفناء الخلفي",
    "option_outdoor_terrace": "الشرفة",
    "option_outdoor_patio": "الفناء",
    "option_outdoor_yard": "الساحة",
    "option_outdoor_pool": "المسبح",
    "option_outdoor_front_garden": "الحديقة الأمامية",
    "discover_section_kitchen": "المطبخ",
    "discover_section_living_room": "غرفة المعيشة",
    "discover_section_bedroom": "غرفة النوم",
    "discover_section_bathroom": "الحمام",
    "discover_section_dining": "غرفة الطعام",
    "discover_section_home_office": "المكتب المنزلي",
    "discover_section_library": "المكتبة",
    "discover_section_hall": "المدخل والممر",
    "discover_section_gaming": "غرفة الألعاب",
    "discover_section_laundry": "غرفة الغسيل",
    "discover_section_villa": "فيلا",
    "discover_section_apartment": "شقة",
    "discover_section_residential": "سكني",
    "discover_section_wall_scenes": "الجدران",
    "discover_section_floors": "الأرضيات",
    "discover_section_garden": "الحديقة",
    "discover_section_outdoor_spaces": "المساحات الخارجية",
    "discover_subtitle_kitchen": "تخطيطات مضيئة، جزر، تخزين وإضاءة عمل دافئة.",
    "discover_subtitle_living_room": "جلوس مريح، جدران مركزية وراحة يومية أنيقة.",
    "discover_subtitle_bedroom": "أسرّة متعددة الطبقات، لوحات هادئة وديكور راقي.",
    "discover_subtitle_bathroom": "مواد سبا، أحواض، بلاط، مرآة وإضاءة ناعمة.",
    "discover_subtitle_dining": "أجواء طعام مع إضاءة مميزة وتشطيبات متوازنة.",
    "discover_subtitle_home_office": "مكاتب إنتاجية، رفوف، تخزين ومناطق عمل هادئة.",
    "discover_subtitle_library": "غرف قراءة مع مكتبات، كتب، ملمس ومزاج.",
    "discover_subtitle_hall": "أفكار مدخل وممر تشكل انطباعاً أولياً.",
    "discover_subtitle_gaming": "غرف غامرة مع شاشات، مقاعد صالة وأجواء.",
    "discover_subtitle_laundry": "مساحات عملية مع تخزين، عدادات، بلاط ومتدفق نظيف.",
    "discover_subtitle_villa": "واجهات فيلا حديثة مع مداخل، زجاج وسحر.",
    "discover_subtitle_house": "أفكار خارجية للبيت للحجوم والمواد وال 접근.",
    "discover_subtitle_apartment": "كتل شقق مع شرفات، إيقاع وحضور في الشارع.",
    "discover_subtitle_office_building": "واجهات مكاتب خارجية مع زجاج، هيكل وتشطيب مهني.",
    "discover_subtitle_retail": "واجهات تجارية مع لافتات جاهزة ومداخل مرحبة.",
    "discover_subtitle_residential": "واجهات سكنية مع مسابح، حجر، حدائق وإضاءة.",
    "discover_subtitle_wall_scenes": "طلاء وتشطيبات جدران في غرف هادئة وجريئة ودافئة.",
    "discover_subtitle_floors": "مواد أرضيات من خشب، حجر، بلاط، سجاد وخرسانة.",
    "discover_subtitle_garden": "تكوينات حديقة مع زراعة، مقاعد، مسارات وضوء.",
    "discover_subtitle_backyard": "أفكار فناء خلفي لتجمعات، زراعة، خصوصية وظل.",
    "discover_subtitle_terrace": "مفاهيم شرفة لتناول الطعام في الهواء الطلق والاسترخاء.",
    "discover_subtitle_patio": "ترتيبات فناء مع تبليط، أثاث، خضرة وضوء.",
    "discover_subtitle_yard": "تحولات فناء مع حركة، مناطق وزراعة ناعمة.",
    "discover_subtitle_pool": "مشاهد مسبح مع تبليط، زراعة، مقاعد وهدوء.",
    "discover_subtitle_front_garden": "مدخل حديقة أمامية يحسّن الوصول والسحر.",
    "discover_subtitle_outdoor_spaces": "مساحات خارجية للترفيه، الاسترخاء، المسبح والمداخل.",
    "gallery_item_bathroom": "الحمام",
    "gallery_item_dining_room": "غرفة الطعام",
    "gallery_item_home_office": "المكتب المنزلي",
    "gallery_item_bright_study": "دراسة مضيئة",
    "gallery_item_library": "المكتبة",
    "gallery_item_hallway": "الممر",
    "gallery_item_game_room": "غرفة الألعاب",
    "gallery_item_laundry": "غرفة الغسيل",
    "gallery_item_pool_house": "بيت المسبح",
    "gallery_item_stone_manor": "قصر حجري",
    "gallery_item_facade_7": "الواجهة 7",
    "gallery_item_soft_ivory": "عاجي ناعم",
    "gallery_item_sage_green": "أخضر الشبت",
    "gallery_item_midnight_blue": "أزرق منتصف الليل",
    "gallery_item_gallery_charcoal": "فحمي للمعرض",
    "gallery_item_terracotta": "تيرا كوتا",
    "gallery_item_dusty_rose": "وردي باهت",
    "gallery_item_natural_oak": "بلوظة طبيعية",
    "gallery_item_walnut": "جوز",
    "gallery_item_marble": "رخام",
    "gallery_item_polished_concrete": "خرسانة مصقولة",
    "gallery_item_chevron": "شيفرون",
    "gallery_item_terracotta_floor": "تيرا كوتا",
    "gallery_item_backyard": "الفناء الخلفي",
    "gallery_item_terrace": "الشرفة",
    "gallery_item_patio": "الفناء",
    "gallery_item_pool": "المسبح",
    "gallery_item_villa_entry": "مدخل الفيلا",
    "example_facade_scaffold_house": "منزل قيد السقالات",
    "example_facade_weathered_house": "منزل متآثر بالعوامل",
    "example_facade_brick_shell": "هيكل طوبي",
    "example_facade_overgrown_cottage": "كوخ متضخم بالنباتات",
    "example_garden_muddy_yard": "ساحة موحلة",
    "example_garden_weedy_yard": "ساحة مليئة بالأعشاب",
    "example_garden_rubble_yard": "ساحة ركام",
    "example_garden_overgrown_corner": "زاوية متضخمة بالنباتات",
    "example_floor_cracked_concrete": "خرسانة متشققة",
    "example_floor_damaged_planks": "ألواح متضررة",
    "example_floor_broken_tile": "بلاط مكسور",
    "example_floor_subfloor": "الأرضية الفرعية",
    "example_paint_raw_concrete": "خرسانة خام",
    "example_paint_peeling_plaster": "لياسة متقشرة",
    "example_paint_worn_white": "باب أبيض بالاء",
    "example_paint_exposed_brick": "طوبي مكشوف",
    "example_interior_empty_room": "غرفة فارغة",
    "example_interior_messy_lounge": "صالة غير مرتبة",
    "example_interior_damaged_room": "غرفة متضررة",
    "example_interior_outdated_kitchen": "مطبخ قديم الطراز",
    "language_system_default": "افتراضي النظام",
    "language_name_en_us": "English (US)",
    "language_name_ar": "العربية",
    "language_name_sv": "Svenska",
    "language_name_de": "Deutsch",
    "language_name_it": "Italiano",
    "language_name_ja": "日本語",
    "language_name_ko": "한국어",
    "language_name_fr": "Français",
    "language_name_pt": "Português",
    "language_name_pt_br": "Português (Brasil)",
    "language_name_es": "Español",
    "language_name_es_mx": "Español (México)",
    "language_name_ru": "Русский",
    "language_name_zh_hans": "简体中文",
    "language_name_zh_hant": "繁體中文",
    "language_name_vi": "Tiếng Việt",
    "my_profile_title": "الملف الشخصي",
    "sign_in_to_account": "سجّل الدخول إلى حسابك",
    "sign_in_to_account_body": "سجّل الدخول لحفظ تصاميمك والوصول إلى لوحتك عبر الأجهزة ومتابعة أنماطك المفضلة.",
    "go_premium": "الترقية للمميز",
    "go_premium_body": "إنشاءات ولوحات غير محدودة",
    "upgrade": "الترقية",
    "account_section": "الحساب",
    "settings_section": "الإعدادات",
    "edit_profile": "تعديل الملف الشخصي",
    "edit_profile_body": "الاسم، الصورة، النبذة",
    "privacy_security": "الخصوصية والأمان",
    "privacy_security_body": "كلمة المرور، البيانات",
    "my_diamonds": "ماساتي",
    "my_diamonds_body": "%1$d ماسة · احصل على المزيد",
    "notifications": "الإشعارات",
    "notifications_body": "مكافآت يومية، تحديثات",
    "preferences_body": "النمط، الثيمات، اللغة",
    "help_faq": "المساعدة والأسئلة الشائعة",
    "help_faq_body": "أدلة الاستخدام",
    "contact_support": "التواصل مع الدعم",
    "contact_support_body": "تحدث معنا",
    "sign_out": "تسجيل الخروج",
    "my_board_title": "الملف الشخصي",
    "generated_tab": "المنشأة",
    "favorites_tab": "المفضلة",
    "sign_in_to_view_board": "سجّل الدخول لعرض لوحتك",
    "sign_in_to_view_board_body": "صورك المنشأة ومفضلاتك محفوظة في حسابك. سجّل الدخول للوصول إليها.",
    "profile_sign_in_benefits": "سجّل الدخول لحفظ تصاميمك والوصول إلى لوحتك عبر الأجهزة ومتابعة أنماطك المفضلة.",
    "profile_sign_in_register": "سجّل الدخول أو أنشئ حساباً",
    "generated_images": "الصور المنشأة",
    "favorites_section": "المفضلة",
    "add_favorite": "إضافة مفضلة",
    "free_badge": "مجاني",
    "google_icon_label": "G",
    "initials_fallback": "م",
    "moodboard_idea_fallback": "فكرة لوحة أجواء",
    "project_save_fallback": "حفظ مشروع",
    "untitled_project": "مشروع بدون عنوان",
    "no_room_type": "نوع غرفة غير محدد",
    "paywall_upgrade_pro": "✦ الترقية إلى PRO",
    "paywall_hero_title": "صمّم باحتراف.\nبلا حدود أبداً.",
    "paywall_hero_subtitle": "أنشئ تصييرات 4K غير محدودة، صدّر بوضوح، وافتح أنماطاً مميزة بلا حدود.",
    "paywall_feat_4k": "تصدير 4K",
    "paywall_feat_4k_sub": "تصييرات فائقة الدقة",
    "paywall_feat_unlimited": "بدون علامة مائية",
    "paywall_feat_unlimited_sub": "تصدير نظيف دائماً",
    "paywall_feat_priority": "طاقة غير محدودة",
    "paywall_feat_priority_sub": "بدون حدود للإنشاء",
    "paywall_feat_portfolio": "المحفظة",
    "paywall_feat_portfolio_sub": "ابنِ مجموعتك",
    "paywall_choose_plan": "اختر خطتك",
    "paywall_trial_note": "3 أيام مجانية تماماً — جرّب كل شيء، ألغِ قبلها ولا تدفع شيئاً.",
    "paywall_cta_start": "✦ ابدأ 3 أيام مجانية ←",
    "paywall_cta_processing": "⏳ جارٍ المعالجة…",
    "paywall_cta_success": "✓ مرحباً بك في Pro!",
    "paywall_cancel_anytime": "✓ يمكنك الإلغاء في أي وقت · بدون التزام",
    "paywall_restore": "استعادة الشراء",
    "paywall_cmp_feature": "الميزة",
    "paywall_cmp_free": "مجاني",
    "paywall_cmp_pro": "✦ PRO",
    "paywall_cmp_renders": "طاقة غير محدودة",
    "paywall_cmp_unlimited": "∞ غير محدود",
    "paywall_cmp_export": "تصدير 4K",
    "paywall_cmp_4k": "مشمول",
    "paywall_cmp_watermark": "علامة مائية",
    "paywall_cmp_yes": "نعم",
    "paywall_cmp_none": "بدون علامة مائية ✓",
    "paywall_cmp_ai": "سرعة الذكاء الاصطناعي",
    "paywall_cmp_standard": "قياسي",
    "paywall_cmp_priority_pro": "أولوية",
    "paywall_plan_annual": "وصول سنوي",
    "paywall_best_value": "🔥 أفضل قيمة",
    "paywall_per_week": "/ أسبوعياً",
    "paywall_save_badge": "🎉 وفّر 89% مقارنة بالأسبوعي",
    "paywall_plan_weekly": "وصول أسبوعي",
    "paywall_plan_monthly": "وصول شهري",
    "paywall_annual_price": "4.78",
    "paywall_annual_detail": "248.65 MAD فوترة مرة واحدة سنوياً",
    "paywall_weekly_price": "44.68",
    "paywall_weekly_detail": "44.68 MAD / أسبوعياً · فوترة أسبوعية",
    "paywall_annual_currency": "MAD",
    "paywall_weekly_currency": "MAD / أسبوعياً",
}

# Preserve order from English file - read it to get the key order
import re
en_path = r'C:\Users\LENOVO\Desktop\HomeDecor AI (App)\app\src\main\res\values\strings.xml'
with open(en_path, 'r', encoding='utf-8') as f:
    en_content = f.read()

# Extract key order from English file
en_keys = re.findall(r'<string name="([^"]+)">', en_content)

for key in en_keys:
    if key in strings:
        val = strings[key]
        # Escape & for XML
        val = val.replace('&', '&amp;')
        lines.append(f'  <string name="{key}">{val}</string>')

# Add any keys not in English file order (shouldn't happen but just in case)
for key in strings:
    if key not in en_keys:
        val = strings[key]
        val = val.replace('&', '&amp;')
        lines.append(f'  <string name="{key}">{val}</string>')

lines.append('</resources>')

output = '\n'.join(lines) + '\n'

with open(path, 'w', encoding='utf-8') as f:
    f.write(output)

# Count lines
print(f'Written {len(lines)} lines')
print(f'File size: {len(output)} bytes')

# Verify
with open(path, 'r', encoding='utf-8') as f:
    verify = f.read()
vkeys = re.findall(r'<string name="([^"]+)">', verify)
print(f'Verified: {len(vkeys)} string keys')
missing = [k for k in en_keys if k not in vkeys]
if missing:
    print(f'Missing {len(missing)} keys: {missing[:10]}')
else:
    print('All English keys present!')
