package com.ismail.homedecorai

object Strings {
    // Navigation
    const val navTools = "Tools"
    const val navDiscover = "Discover"
    const val navUpgrade = "Upgrade"
    const val navProfile = "Profile"
    const val navMyBoard = "My Board"
    const val navCreate = "Create"

    // Home / Landing section (desktop)
    const val homeHeadline = "Design your dream space with AI"
    const val homeSubtitle = "Upload a photo of any room and watch it transform. Instant mockups, unlimited styles, professional results."
    const val homeCtaPrimary = "Upload your room"
    const val homeCtaSecondary = "Explore tools"
    const val homeBeforeLabel = "Before"
    const val homeAfterLabel = "After"
    const val homeFeature1Title = "AI-Powered"
    const val homeFeature1Body = "Smart AI understands your space and applies design styles that actually work."
    const val homeFeature2Title = "Instant Results"
    const val homeFeature2Body = "See your redesigned room in seconds. No waiting, no complexity."
    const val homeFeature3Title = "Unlimited Styles"
    const val homeFeature3Body = "From minimalist to maximalist, Scandinavian to boho. Try them all."
    const val homeTrust1 = "Free to start"
    const val homeTrust2 = "No credit card"
    const val homeTrust3 = "Cancel anytime"

    // Tools Screen
    const val proUpper = "PRO"
    const val tryThis = "Try this"
    const val a11yOpenDiamondStore = "Open diamond store"
    fun a11yToolCard(title: String, description: String) = "$title: $description"

    // Discover Screen
    const val discoverStylesTitle = "Discover"
    const val discoverHeroBody = "Find inspiration for your next redesign"
    const val back = "Back"
    fun ideasCount(count: Int) = "$count ideas"
    const val seeAll = "See all"
    const val createWithStyle = "Create with this style"
    const val favorited = "Favorited"
    const val favorite = "Favorite"
    const val addToMoodboard = "Save to board"
    const val toastFavoriteAdded = "Added to favorites"
    const val toastFavoriteRemoved = "Removed from favorites"
    const val toastMoodboardAdded = "Saved to your board"
    fun a11yDiscoverCluster(clusterLabel: String) = "Cluster: $clusterLabel"
    fun a11ySeeAll(sectionTitle: String) = "See all $sectionTitle"
    fun a11yGalleryCard(itemTitle: String, itemCategory: String) = "$itemTitle, $itemCategory"

    // Profile Screen
    const val myProfileTitle = "Profile"
    const val profileSubtitle = "Manage your account and preferences"
    const val settings = "Settings"
    const val accountSection = "Account"
    const val editProfile = "Edit profile"
    const val editProfileBody = "Update your name and photo"
    const val privacySecurity = "Privacy & security"
    const val privacySecurityBody = "Manage your data and privacy settings"
    const val myDiamonds = "My Diamonds"
    fun myDiamondsBody(diamonds: Int) = "$diamonds diamonds available"
    const val subscriptionStatus = "Subscription"
    const val currentPlan = "Current Plan"
    const val currentPlanBodyPro = "You have unlimited generations"
    const val currentPlanBodyFree = "Upgrade for unlimited generations"
    const val profileSignInBody = "Sign in to save your projects and access your diamonds across devices."
    const val profileSignInRegister = "Sign In / Register"
    const val profileStatusDiamonds = "Diamonds"
    const val profileStatusPlan = "Plan"
    const val profileStatusSaved = "Saved"
    const val freePlan = "Free"
    const val initialsFallback = "??"
    const val freeBadge = "FREE"
    const val accountConnected = "Account connected"
    const val profileProMember = "Pro Member"
    const val profileSavedDesigns = "Saved Designs"
    const val profileNoDesignsYet = "No designs yet. Start creating!"
    const val profileViewAllDesigns = "View all designs"

    // Settings Screen
    const val language = "Language"
    const val rateUs = "Rate us"
    const val contactSupport = "Contact support"
    const val deleteInformation = "Delete information"
    fun versionLabel(version: String) = "Version $version"
    const val toastLanguageSelected = "Language updated"
    const val languageSystemDefault = "System default"
    fun a11yLanguageSelected(label: String) = "$label (selected)"
    const val a11yCheckIcon = "Selected"

    // Dialogs
    const val feedbackDialogTitle = "Contact Support"
    const val feedbackHint = "Describe your issue or suggestion..."
    const val feedbackSending = "Sending..."
    const val feedbackSend = "Send"
    const val cancel = "Cancel"
    const val deleteAccountTitle = "Delete Account"
    const val deleteAccountBody = "Are you sure you want to delete your account? This action cannot be undone."
    const val deletingAccount = "Deleting..."
    const val deleteAccountConfirm = "Delete"
    const val retry = "Retry"
    const val dismiss = "Dismiss"

    // Discover clusters
    fun discoverCluster(cluster: String): String = when (cluster) {
        "interior" -> "Interior"
        "architecture" -> "Architecture"
        "landscape" -> "Landscape"
        else -> cluster.replaceFirstChar { it.uppercase() }
    }

    // Discover sections
    fun discoverSectionTitle(sectionId: String): String = when (sectionId) {
        "living-room" -> "Living Room"
        "bedroom" -> "Bedroom"
        "kitchen" -> "Kitchen"
        "bathroom" -> "Bathroom"
        "office" -> "Office"
        "dining" -> "Dining Room"
        "modern-house" -> "Modern House"
        "classic-house" -> "Classic House"
        "apartment" -> "Apartment"
        "villa" -> "Villa"
        "cabin" -> "Cabin"
        "garden" -> "Garden"
        "patio" -> "Patio"
        "pool" -> "Pool Area"
        "rooftop" -> "Rooftop"
        "balcony" -> "Balcony"
        else -> sectionId.replaceFirstChar { it.uppercase() }
    }

    // Gallery items
    fun galleryItemTitle(itemId: String): String {
        val base = itemId.substringBeforeLast("-", itemId).replace("-", " ")
        return base.replaceFirstChar { it.uppercase() }
    }

    fun galleryItemCategory(category: String): String = category
        .replaceFirstChar { it.uppercase() }

    // Accessibility labels for gallery cards
    fun a11yInspirationImage(sectionTitle: String): String = "$sectionTitle inspiration image"

    // My Board
    const val myBoardTitle = "My Board"
    const val boardSignInCta = "Sign in to save your designs."
    const val boardPreviewLocked = "Sign in to view"
    const val boardSignInToUnlock = "Sign in to unlock"
    const val boardEmptyGenerated = "No designs yet"
    const val boardEmptyGeneratedBody = "Create your first AI design and it will appear here."
    const val boardEmptyFavorites = "No favorites yet"
    const val boardEmptyFavoritesBody = "Save designs you love and they'll show up here."
    const val boardEmptyProjects = "No projects yet"
    const val boardEmptyProjectsBody = "Create projects to organize your design collections."
    const val startADesign = "Start a design"
    const val exploreDiscover = "Explore Discover"
    const val generatedTab = "Generated"
    const val favoritesTab = "Favorites"
    const val projectsTab = "Projects"
    const val generatedImages = "Generated Images"
    const val favoritesSection = "Favorites"
    const val savedProjects = "Projects"
    const val boardGuestHeadline = "Your design journey starts here"
    const val boardGuestSubtitle = "Sign in to save, organize, and access your designs from anywhere"
    const val boardGuestBenefit1 = "Save unlimited designs to your board"
    const val boardGuestBenefit2 = "Access your designs on any device"
    const val boardGuestBenefit3 = "Organize into custom projects"
    const val boardSampleLivingRoom = "Modern Living Room"
    const val boardSampleBedroom = "Cozy Bedroom"
    const val boardSampleKitchen = "Minimalist Kitchen"
    const val boardSampleBathroom = "Luxury Bathroom"
    const val boardSampleOffice = "Home Office"
    const val boardSampleGarden = "Garden Terrace"
    const val boardSampleCreated = "Created by AI"
    const val boardSampleStyle = "Scandinavian"
    const val boardViewAll = "View all"
    const val boardUpgradeToUnlock = "Upgrade to Pro to unlock all features"

    // Settings sections
    const val settingsSectionAccount = "Account"
    const val settingsSectionApp = "App"
    const val settingsSectionPurchases = "Purchases"
    const val settingsSectionSupport = "Support"
    const val settingsSectionLegal = "Legal"
    const val myDiamondsBodySettings = "Diamonds available"
    const val diamondStore = "Diamond Store"
    const val diamondStoreBody = "Buy diamonds for more generations"
    const val restorePurchases = "Restore Purchases"
    const val restorePurchasesBody = "Restore your previous purchases"
    const val faq = "FAQ"
    const val faqBody = "Frequently asked questions"
    const val shareApp = "Share App"
    const val shareAppBody = "Share with friends and family"
    const val rateUsBody = "Rate us on the App Store"
    const val feedbackBody = "Send us your feedback"
    const val termsBody = "Terms of Service"
    const val privacyBody = "Privacy Policy"
    const val logOut = "Log Out"
    const val logOutBody = "Sign out of your account"
    const val close = "Close"
    const val settingsAccountDescription = "Your profile and preferences"
    const val settingsAppDescription = "Customize your experience"
    const val settingsPurchasesDescription = "Manage your subscriptions"
    const val settingsSupportDescription = "Get help and share feedback"
    const val settingsLegalDescription = "Policies and terms"
    const val settingsAppearance = "Appearance"
    const val settingsAppearanceBody = "Dark mode and display"

    // Profile sections
    const val preferencesSection = "Preferences"
    const val supportSection = "Support"
    const val legalSection = "Legal"
    const val appInfoSection = "App Info"
    const val helpCenter = "Help Center"
    const val helpCenterBody = "Browse FAQs and guides"
    const val contactUs = "Contact Us"
    const val contactUsBody = "Get in touch with our team"
    const val rateApp = "Rate App"
    const val rateAppBody = "Rate us on the App Store"
    const val termsOfService = "Terms of Service"
    const val termsOfServiceBody = "Review our terms"
    const val privacyPolicyLabel = "Privacy Policy"
    const val privacyPolicyBody = "How we handle your data"
    const val openSourceLicenses = "Open Source Licenses"
    const val openSourceLicensesBody = "Third-party software licenses"
    const val appVersion = "Version"
    const val appBuildNumber = "Build"
    const val savedDesignsEmptyCta = "Explore Discover"
    const val themeLabel = "Theme"
    const val themeBody = "Dark mode and display"
    const val notificationsLabel = "Notifications"
    const val notificationsBody = "Manage push and email alerts"
    const val languageLabel = "Language"
    const val languageBody = "Change app language"

    // Paywall Sheet - 5 Step Flow
    const val proA11yClose = "Close"
    const val paywallA11yBack = "Go back"

    // Step 1: Unlimited Makeovers
    const val pwS1Heading = "Create unlimited room"
    const val pwS1HeadingHighlight = "makeovers"
    const val pwS1Benefit1 = "Unlimited redesign generations"
    const val pwS1Benefit2 = "Unlimited style experiments"
    const val pwS1Benefit3 = "Unlimited inspiration ideas"
    const val pwS1Benefit4 = "Unlimited saved variations"
    const val pwS1Cta = "Try Premium for \$0.00"
    const val pwS1SocialProof = "Trusted by 50,000+ home design enthusiasts"

    // Step 2: Reminder
    const val pwS2Heading = "When should we remind you before your trial ends?"
    const val pwS2Option1 = "2 days before"
    const val pwS2Option2 = "3 days before"
    const val pwS2Info = "Easy to cancel, no fees before trial ends."
    const val pwS2Cta = "Start free trial"

    // Step 3: Comparison
    const val pwS3Heading = "Why upgrade?"
    const val pwS3ColFeature = "Feature"
    const val pwS3ColFree = "Free"
    const val pwS3ColPremium = "Premium"
    const val pwS3Row1Feature = "AI room redesigns"
    const val pwS3Row1Free = "3/day"
    const val pwS3Row2Feature = "HD exports"
    const val pwS3Row2Free = "\u2014"
    const val pwS3Row3Feature = "No watermark"
    const val pwS3Row3Free = "\u2014"
    const val pwS3Row4Feature = "Premium interior styles"
    const val pwS3Row4Free = "Limited"
    const val pwS3Row5Feature = "Faster generation"
    const val pwS3Row5Free = "\u2014"
    const val pwS3Row6Feature = "Save unlimited projects"
    const val pwS3Row6Free = "\u2014"
    const val pwS3Recommendation = "Most users upgrade for unlimited redesigns + HD exports."
    const val pwS3Cta = "Try Premium for \$0.00"

    // Step 4: Plans
    const val pwS4Heading = "Choose the plan after your 7-day free trial"
    const val pwS4PlanYearlyTitle = "Yearly Premium"
    const val pwS4PlanYearlyPrice = "\$39.99"
    const val pwS4PlanYearlyPer = "/year"
    const val pwS4PlanYearlyDetail = "Only \$3.33 / month"
    const val pwS4PlanYearlyBadge = "Most Popular"
    const val pwS4PlanYearlySavings = "Save 58%"
    const val pwS4PlanMonthlyTitle = "Monthly Premium"
    const val pwS4PlanMonthlyPrice = "\$7.99"
    const val pwS4PlanMonthlyPer = "/month"
    const val pwS4PlanFamilyTitle = "Family / Team"
    const val pwS4PlanFamilyPrice = "\$59.99"
    const val pwS4PlanFamilyPer = "/year"
    const val pwS4PlanFamilyDetail = "Up to 5 users"
    const val pwS4Cta = "Start 7-day free trial"
    const val pwS4Trust = "Cancel anytime."

    // Step 5: Checkout
    const val pwS5Heading = "Your subscription is handled securely."
    const val pwS5Badge = "Secure Checkout"
    const val pwS5PlanTitle = "Yearly Premium"
    const val pwS5PlanSubtitle = "7-day free trial"
    const val pwS5TrialPeriod = "Trial period"
    const val pwS5TrialValue = "7 days free"
    const val pwS5Then = "Then"
    const val pwS5RenewalDate = "Renewal date"
    const val pwS5Payment = "Payment"
    const val pwS5PaymentValue = "Secure web checkout"
    const val pwS5BenefitsTitle = "Included benefits"
    const val pwS5Benefit1 = "Unlimited AI redesigns"
    const val pwS5Benefit2 = "HD exports"
    const val pwS5Benefit3 = "No watermark"
    const val pwS5Benefit4 = "Premium styles"
    const val pwS5Benefit5 = "Unlimited saved projects"
    const val pwS5Benefit6 = "Faster processing"
    const val pwS5Cta = "Join waitlist"
    const val pwS5Trust = "Cancel anytime. No commitment."
    const val pwS5Legal = "By subscribing, you agree to our Terms of Service and Privacy Policy."
    const val pwS5Restore = "Restore purchases"

    // Legacy aliases used by SharedPaywallSheet
    const val paywallV3Headline = pwS1Heading
    const val paywallV3Subtitle = "Unlimited generations, premium styles, and HD exports"
    const val paywallV3TrialNote = "7-day free trial, cancel anytime"
    const val paywallV3Before = "Before"
    const val paywallV3After = "After"
    const val paywallV3BenefitGenerations = "Unlimited generations"
    const val paywallV3BenefitExport = "HD export"
    const val paywallV3BenefitWatermark = "No watermark"
    const val paywallV3BenefitSpeed = "Priority speed"
    const val paywallV3BenefitStyles = "All styles"
    const val paywallV3BenefitHistory = "History access"
    const val paywallV3PlanYearly = "Yearly"
    const val paywallV3PlanPerYear = "/year"
    const val paywallV3PlanAnnualDetail = "Billed annually. Best value."
    const val paywallV3PlanWeekly = "Weekly"
    const val paywallV3PlanPerWeek = "/week"
    const val paywallV3PlanWeeklyDetail = "Billed weekly."
    const val paywallV3PlanMonthly = "Monthly"
    const val paywallV3PlanPerMonth = "/month"
    const val paywallV3PlanMonthlyDetail = "Billed monthly."
    const val paywallV3PlanFamily = "Family"
    const val paywallV3PlanFamilyDetail = "Share with up to 5 family members."
    const val paywallV3PlanBestValue = "Best value"
    const val paywallV3Cta = pwS1Cta
    const val paywallV3Trust = "Cancel anytime. No commitment."
    const val paywallV3Restore = "Restore purchases"
    const val paywallV3JoinWaitlist = "Join waitlist"
    const val paywallV3ContinueToCheckout = "Continue to checkout"
    const val terms = "Terms"
    const val privacyPolicy = "Privacy Policy"

    // Upgrade Screen
    const val proActivated = "Pro Activated"
    const val activeProAccess = "You have full access to all Pro features"
    const val upgradeV3Headline = "Unlock Your Full Design Studio"
    const val upgradeV3Subtitle = "Transform any space with unlimited AI power, premium styles, and professional exports"
    const val upgradeV3TrialBadge = "7-day free trial"
    const val upgradeV3Trust = "Cancel anytime. No commitment."
    const val upgradeV3Before = "Before"
    const val upgradeV3After = "After"
    const val upgradeV3BenefitGenerations = "Unlimited AI generations"
    const val upgradeV3BenefitExport = "Export in HD quality"
    const val upgradeV3BenefitNoWatermark = "No watermark on results"
    const val upgradeV3BenefitSpeed = "Priority processing speed"
    const val upgradeV3BenefitStyles = "Access all premium styles"
    const val upgradeV3BenefitHistory = "Save your design history"
    const val upgradeV3Cta = "Join waitlist"
    const val upgradeV3Secondary = "Compare plans"
    const val upgradeV3JoinWaitlist = "Join waitlist"
    const val upgradePlanMonthly = "Monthly"
    const val upgradePlanMonthlyPrice = "$7.99"
    const val upgradePlanMonthlyPeriod = "/month"
    const val upgradePlanYearly = "Yearly"
    const val upgradePlanYearlyPrice = "$39.99"
    const val upgradePlanYearlyPeriod = "/year"
    const val upgradePlanYearlySave = "Save 58%"
    const val upgradePlanBestValue = "Best Value"
    const val upgradePlanFamily = "Family / Team"
    const val upgradePlanFamilyPrice = "$59.99"
    const val upgradePlanFamilyPeriod = "/year"
    const val upgradePlanFamilySubtitle = "Up to 5 users"
    const val upgradeBenefitUnlimited = "Unlimited AI generations"
    const val upgradeBenefitExport = "HD & 4K export"
    const val upgradeBenefitNoWatermark = "No watermark on any design"
    const val upgradeBenefitPriority = "Priority processing"
    const val upgradeBenefitStyles = "All 50+ premium styles"
    const val upgradeBenefitHistory = "Full design history"
    const val upgradeBenefitSupport = "Priority support"
    const val upgradeBenefitUpdates = "Early access to new features"
    const val upgradeWaitlistNote = "Payment not ready yet. Join the waitlist to be notified when we launch."
    const val upgradeTestimonial1 = "This app completely transformed how I visualize my room makeovers."
    const val upgradeTestimonial1Author = "Sarah M., Interior Designer"
    const val upgradeTestimonial2 = "The AI designs are incredibly realistic. Saved me thousands in consultations."
    const val upgradeTestimonial2Author = "James K., Homeowner"
    const val upgradeFeatureCompare = "What you get with Pro"
    const val upgradeFreePlan = "Free"
    const val upgradeProPlan = "Pro"
    const val upgradeCompareGenerations = "AI Generations"
    const val upgradeCompareGenerationsFree = "1 per day"
    const val upgradeCompareGenerationsPro = "Unlimited"
    const val upgradeCompareExport = "Export Quality"
    const val upgradeCompareExportFree = "Standard"
    const val upgradeCompareExportPro = "HD & 4K"
    const val upgradeCompareWatermark = "Watermark"
    const val upgradeCompareWatermarkFree = "Yes"
    const val upgradeCompareWatermarkPro = "None"
    const val upgradeCompareSpeed = "Processing"
    const val upgradeCompareSpeedFree = "Standard"
    const val upgradeCompareSpeedPro = "Priority"
    const val upgradeCompareStyles = "Design Styles"
    const val upgradeCompareStylesFree = "5 basic"
    const val upgradeCompareStylesPro = "50+ premium"
    const val upgradeCompareSupport = "Support"
    const val upgradeCompareSupportFree = "Community"
    const val upgradeCompareSupportPro = "Priority"

    // Web Wizard
    const val wizardStepUpload = "Upload Photo"
    const val wizardStepRoom = "Room Type"
    const val wizardStepStyle = "Style"
    const val wizardStepReview = "Review"
    const val wizardUploadTitle = "Upload a photo of your space"
    const val wizardUploadSubtitle = "Drag and drop an image, or click to browse"
    const val wizardChooseImage = "Choose image"
    const val wizardTryExample = "Try with an example"
    const val wizardUploadChange = "Change photo"
    const val wizardRoomTitle = "What type of space is this?"
    const val wizardRoomSubtitle = "Select the option that best describes your space"
    const val wizardStyleTitle = "Choose a design style"
    const val wizardStyleSubtitle = "Pick a style to apply to your space"
    const val wizardReviewTitle = "Review your design"
    const val wizardReviewSubtitle = "Check your selections before generating"
    const val wizardReviewPhoto = "Photo"
    const val wizardReviewRoom = "Room"
    const val wizardReviewStyle = "Style"
    const val wizardGenerate = "Generate Design"
    const val wizardGenerating = "Generating..."
    const val wizardBack = "Back"
    const val wizardNext = "Next"
    const val wizardJoinWaitlist = "Join waitlist"
    const val wizardComingSoon = "AI generation coming soon"
    const val wizardComingSoonBody = "Our AI engine is being finalized. Join the waitlist to be first in line when it launches."
    const val wizardWaitlistSuccess = "You're on the list!"
    const val wizardWaitlistSuccessBody = "We'll notify you as soon as AI generation is available."
    const val wizardTryAgain = "Try again"
    const val wizardErrorPhoto = "Please upload a photo to continue"
    const val wizardErrorRoom = "Please select a room type"
    const val wizardErrorStyle = "Please select a style"
    const val wizardClose = "Close"
    const val wizardExampleRoom = "Empty living room"
    const val wizardExampleGarden = "Backyard garden"
    const val wizardExampleExterior = "House facade"
    const val wizardDropHere = "Drop your image here"
    const val wizardImageFormats = "JPG, PNG or WebP"
    const val wizardPhotoSelected = "Photo selected"
    const val wizardRemove = "Remove"
    const val wizardReady = "Ready"
    const val wizardGeneratingBody = "This may take a moment..."
    const val wizardErrorTitle = "Generation Failed"
    const val wizardWaitlistBenefit1 = "Be first to try AI generation"
    const val wizardWaitlistBenefit2 = "Get free credits at launch"
    const val wizardWaitlistBenefit3 = "Exclusive early access"
    const val wizardWaitlistEmailLabel = "Email address"
    const val wizardWaitlistEmailPlaceholder = "you@example.com"
    const val wizardWaitlistEmailError = "Please enter a valid email"

    // Discover hover overlay
    const val discoverPreview = "Preview"
    const val discoverUseStyle = "Use Style"
    const val discoverSave = "Save"

    // Image picker
    const val uploadPhotoArea = "Upload photo area"
    const val openGallery = "Open gallery"
    const val takePhoto = "Take photo"
    const val galleryLabel = "Gallery"
    const val cameraLabel = "Camera"
    const val addPhoto = "Add photo"
    const val photosLabel = "Photos"

    // Tool titles and descriptions
    fun toolTitle(toolId: String): String = when (toolId) {
        "interior" -> "Interior Design"
        "facade" -> "Exterior Design"
        "garden" -> "Garden Design"
        "paint" -> "Smart Wall Paint"
        "floor" -> "Floor Design"
        "layout" -> "Layout Makeover"
        "replace" -> "Replace Furniture"
        "reference" -> "Reference Style"
        else -> toolId.replaceFirstChar { it.uppercase() }
    }

    fun toolDescription(toolId: String): String = when (toolId) {
        "interior" -> "Redesign any room with AI-powered interior concepts"
        "facade" -> "Transform your home's exterior with modern facade styles"
        "garden" -> "Plan and visualize your dream garden landscape"
        "paint" -> "Preview smart paint colors on your walls instantly"
        "floor" -> "Explore premium flooring from hardwood to marble tile"
        "layout" -> "Optimize room layout for better flow and functionality"
        "replace" -> "Swap furniture and decor with AI-generated alternatives"
        "reference" -> "Use any reference image to guide your design direction"
        else -> "Explore this tool to enhance your space"
    }

    // Loading & Error
    const val loadingContent = "Loading..."
    const val errorGeneric = "Something went wrong"
}
